import type { TheoryQuestion } from "@/domain/types";

export const agentArchitectureTheory: TheoryQuestion[] = [
  {
    id: "t-aa-01",
    domain: "agent-architecture",
    question: "In the agentic loop, what does `stop_reason: \"end_turn\"` signify?",
    options: [
      { letter: "A", text: "The model hit its `max_tokens` limit and the response was truncated", correct: false },
      { letter: "B", text: "The model has nothing further to do, and the loop should return the result", correct: true },
      { letter: "C", text: "The model is requesting that one or more tools be executed", correct: false },
      { letter: "D", text: "The `max_iterations` backstop has been reached", correct: false },
    ],
    correct: "B",
    explanation: "`end_turn` means the model has nothing further to do and the result should be returned. It is the only trustworthy completion signal — tool requests are signaled by `stop_reason == \"tool_use\"` instead.",
  },
  {
    id: "t-aa-02",
    domain: "agent-architecture",
    question: "Why must an agentic application re-send the entire message history on every API call?",
    options: [
      { letter: "A", text: "Only the latest user turn is actually needed; the full history is sent purely to improve prompt-cache hit rates", correct: false },
      { letter: "B", text: "The model persists memory between calls, but only for the system prompt", correct: false },
      { letter: "C", text: "The model is stateless and holds no memory between calls — context exists only in what the application resubmits each time", correct: true },
      { letter: "D", text: "The messages array is required by the SDK but is ignored by the model after the first call", correct: false },
    ],
    correct: "C",
    explanation: "The model holds no memory between calls, so every request re-sends the system prompt, every prior turn, and every tool result. Anything the model needs to \"recall\" must be in the messages array you send.",
  },
  {
    id: "t-aa-03",
    domain: "agent-architecture",
    question: "What is the correct role of a `max_iterations` cap in an agentic loop?",
    options: [
      { letter: "A", text: "A backstop against runaway loops (e.g., endless tool-error retries) — never the primary completion criterion", correct: true },
      { letter: "B", text: "The primary stop condition, since `stop_reason` can be unreliable", correct: false },
      { letter: "C", text: "A way to guarantee the model emits `end_turn` within a fixed number of turns", correct: false },
      { letter: "D", text: "Unnecessary once `stop_reason == \"end_turn\"` is handled correctly", correct: false },
    ],
    correct: "A",
    explanation: "A `max_iterations` cap is good practice, but only as a backstop against runaway loops — iteration count has no semantic relationship to task completion. Tripping the backstop should be treated as an error condition, not success.",
  },
  {
    id: "t-aa-04",
    domain: "agent-architecture",
    question: "What is the primary function of the `description` field in an `AgentDefinition`?",
    options: [
      { letter: "A", text: "Human-readable documentation for maintainers of the agent codebase", correct: false },
      { letter: "B", text: "Text that is appended to the subagent's system prompt at invocation time", correct: false },
      { letter: "C", text: "A unique identifier used for routing and logging", correct: false },
      { letter: "D", text: "The input a coordinator's routing model reads to decide whether to delegate to this subagent", correct: true },
    ],
    correct: "D",
    explanation: "The `description` is not documentation — it is what a coordinator reads to choose between subagents, so it must precisely describe scope and boundaries. The unique routing/logging identifier is `name`, not `description`.",
  },
  {
    id: "t-aa-05",
    domain: "agent-architecture",
    question: "How many tools should a well-scoped subagent typically have in `allowed_tools`, and why?",
    options: [
      { letter: "A", text: "1–2, because any more creates prompt/tool crosstalk", correct: false },
      { letter: "B", text: "4–6, because tool-selection reliability degrades as the tool list grows", correct: true },
      { letter: "C", text: "10–15, to make sure the subagent is never missing a capability", correct: false },
      { letter: "D", text: "There is no recommended range — tool count does not affect selection accuracy", correct: false },
    ],
    correct: "B",
    explanation: "A well-scoped subagent typically has 4–6 tools. Over-broad lists reduce selection accuracy: an agent with 20 loosely-related tools picks a plausible-but-wrong one more often than an agent with 5 tightly-scoped ones.",
  },
  {
    id: "t-aa-06",
    domain: "agent-architecture",
    question: "When a coordinator invokes a subagent via the `Task` tool, what context does the subagent start with?",
    options: [
      { letter: "A", text: "A blank context containing only what the coordinator explicitly put in the `Task` prompt", correct: true },
      { letter: "B", text: "The coordinator's full conversation history, inherited automatically", correct: false },
      { letter: "C", text: "A shared memory space visible to all subagents in the system", correct: false },
      { letter: "D", text: "The coordinator's system prompt plus the most recent user message", correct: false },
    ],
    correct: "A",
    explanation: "Subagents do not inherit the coordinator's conversation history and have no shared memory — each invocation starts blank with only the `Task` prompt contents. This is why a vague delegation prompt produces a vague result.",
  },
  {
    id: "t-aa-07",
    domain: "agent-architecture",
    question: "What happens when a coordinator issues multiple `Task` calls in a single response?",
    options: [
      { letter: "A", text: "They execute sequentially in the order listed", correct: false },
      { letter: "B", text: "Only the first call is honored; the rest are dropped", correct: false },
      { letter: "C", text: "They are queued and executed one per subsequent coordinator turn", correct: false },
      { letter: "D", text: "The subagents run in parallel, and the coordinator receives all results before proceeding", correct: true },
    ],
    correct: "D",
    explanation: "Multiple `Task` calls in one coordinator response run in parallel, and the coordinator gets all results before proceeding. Dispatching independent subtasks together is the primary latency-reduction lever in hub-and-spoke systems.",
  },
  {
    id: "t-aa-08",
    domain: "agent-architecture",
    question: "What must a coordinator's own `allowed_tools`/`allowedTools` include for it to be able to spawn subagents?",
    options: [
      { letter: "A", text: "`fork_session`", correct: false },
      { letter: "B", text: "Every tool that its subagents use", correct: false },
      { letter: "C", text: "The `Task` tool (which the Claude Code UI now calls the `Agent` tool)", correct: true },
      { letter: "D", text: "A `delegate` permission flag set on each `AgentDefinition`", correct: false },
    ],
    correct: "C",
    explanation: "Delegation happens via the `Task` tool (called `Agent` in the Claude Code UI), so the coordinator must have `Task` in its own tool list or it has no mechanism to spawn subagents at all. It does not need the subagents' own tools.",
  },
  {
    id: "t-aa-09",
    domain: "agent-architecture",
    question: "When a session's prior tool results have gone stale because files changed since they were captured, what is the recommended approach?",
    options: [
      { letter: "A", text: "`--resume` the session and let the agent detect the changes on its own", correct: false },
      { letter: "B", text: "Start a new session seeded with a compact structured summary instead of resuming", correct: true },
      { letter: "C", text: "Use `fork_session` so the stale context stays isolated on the other branch", correct: false },
      { letter: "D", text: "Resume the session but raise `max_iterations` so it can re-explore the whole codebase", correct: false },
    ],
    correct: "B",
    explanation: "Resuming on stale tool results risks the model treating outdated reads as current, so a fresh session seeded with a compact structured summary is more reliable. `--resume` is right only when prior context is mostly still valid; `fork_session` is for branching independent lines of work from a shared baseline.",
  },
  {
    id: "t-aa-10",
    domain: "agent-architecture",
    question: "Which hook runs before a tool call executes, and what can it do?",
    options: [
      { letter: "A", text: "`PreToolUse` — it can inspect the proposed call and block or redirect it", correct: true },
      { letter: "B", text: "`PostToolUse` — it can veto the call before it is dispatched", correct: false },
      { letter: "C", text: "`PreToolUse` — it can only log the call, not alter it", correct: false },
      { letter: "D", text: "`PostToolUse` — it normalizes the tool's arguments before the tool runs", correct: false },
    ],
    correct: "A",
    explanation: "`PreToolUse` intercepts a tool call before execution and can block or redirect it (e.g., routing an over-limit refund to escalation). `PostToolUse` runs after the tool returns and can normalize or trim the result before the model sees it.",
  },
  {
    id: "t-aa-11",
    domain: "agent-architecture",
    question: "Per the page's governing rule, which class of rules should be enforced with hooks rather than prompt instructions?",
    options: [
      { letter: "A", text: "Tone and style preferences", correct: false },
      { letter: "B", text: "Anything the system prompt already states clearly", correct: false },
      { letter: "C", text: "Rules the model has previously violated at least once", correct: false },
      { letter: "D", text: "Financial, legal, and safety-critical rules", correct: true },
    ],
    correct: "D",
    explanation: "Prompt instructions are probabilistic with a non-zero failure rate, while hooks enforce rules in code with 100% deterministic compliance. If a mistake is financial, legal, or safety-critical, put a hook in front of it; preference, tone, and style can stay as prompt instructions.",
  },
  {
    id: "t-aa-12",
    domain: "agent-architecture",
    question: "For which kind of task is dynamic (adaptive) decomposition the right strategy?",
    options: [
      { letter: "A", text: "Repeatable extraction tasks with a known, fixed shape", correct: false },
      { letter: "B", text: "Any task that requires more than three steps", correct: false },
      { letter: "C", text: "Open-ended investigation where each step's scope emerges from the previous step's findings", correct: true },
      { letter: "D", text: "Tasks where reproducibility across runs is the top priority", correct: false },
    ],
    correct: "C",
    explanation: "Dynamic decomposition suits open-ended investigation, debugging, or research where the subtask structure cannot be predetermined — each step's results determine what the next step should be. Known, repeatable task shapes and high reproducibility are the domain of fixed pipelines.",
  },
  {
    id: "t-aa-13",
    domain: "agent-architecture",
    question: "What problem does splitting code review into a per-file pass followed by a cross-file pass avoid?",
    options: [
      { letter: "A", text: "Context isolation between subagents", correct: false },
      { letter: "B", text: "Attention dilution — one giant prompt makes every file compete for the model's attention simultaneously, so subtle issues get missed", correct: true },
      { letter: "C", text: "Prompt/tool crosstalk from imprecise system-prompt wording", correct: false },
      { letter: "D", text: "Coverage gaps caused by too-narrow decomposition", correct: false },
    ],
    correct: "B",
    explanation: "Multi-pass code review is the canonical fixed pipeline: a single prompt containing every file dilutes the model's attention across all of it at once. The two-pass split forces focused attention per file, then a dedicated pass for cross-cutting integration issues.",
  },
  {
    id: "t-aa-14",
    domain: "agent-architecture",
    question: "Which error category is retryable, and what is the correct response to it?",
    options: [
      { letter: "A", text: "Transient (e.g., timeout, HTTP 503, rate limit) — retry with exponential backoff", correct: true },
      { letter: "B", text: "Validation — retry the same input a bounded number of times", correct: false },
      { letter: "C", text: "Business — retry after escalating to a human", correct: false },
      { letter: "D", text: "Permission — retry with backoff until access is granted", correct: false },
    ],
    correct: "A",
    explanation: "Only transient errors are retryable, with exponential backoff (typically 1–2 local retries inside the subagent before propagating). Validation errors need the input fixed, business errors need an explanation and alternative path, and permission errors must be escalated.",
  },
  {
    id: "t-aa-15",
    domain: "agent-architecture",
    question: "Which error-handling anti-pattern does the page identify as the most dangerous, and why?",
    options: [
      { letter: "A", text: "Infinite retries, because they turn a transient blip into a hang", correct: false },
      { letter: "B", text: "Generic `operation failed` strings, because the coordinator cannot branch on them", correct: false },
      { letter: "C", text: "Silent suppression — treating a failed call's empty result as a successful `no data found`, because it looks identical to success downstream", correct: true },
      { letter: "D", text: "Aborting the entire workflow on one subtask's failure, because partial results get discarded", correct: false },
    ],
    correct: "C",
    explanation: "Silent suppression is called the most dangerous anti-pattern because a failed call disguised as an empty-but-successful result is indistinguishable from real success downstream. The other options are also anti-patterns, but only silent suppression gets the \"most dangerous\" label.",
  },
  {
    id: "t-aa-16",
    domain: "agent-architecture",
    question: "What does it mean that the agentic loop is \"model-driven\"?",
    options: [
      { letter: "A", text: "The application selects the next tool and the model only formats the arguments", correct: false },
      { letter: "B", text: "The loop follows a fixed, pre-scripted tool sequence defined at design time", correct: false },
      { letter: "C", text: "Claude decides which tool to call next by reasoning over the current context, rather than following a hardcoded decision tree", correct: true },
      { letter: "D", text: "The model manages the loop's iteration count internally, so no backstop is needed", correct: false },
    ],
    correct: "C",
    explanation: "The model reasons over the current context to choose each next step instead of following a fixed decision tree — that adaptivity is the whole point of an agent. It is also why `stop_reason` carries so much weight: you aren't dictating each step, so you need a reliable signal that the model is finished.",
  },
  {
    id: "t-aa-17",
    domain: "agent-architecture",
    question: "In the agentic loop, what should the application do when a response arrives with `stop_reason: \"tool_use\"`?",
    options: [
      { letter: "A", text: "Execute the requested tool(s), append the `tool_result` block(s) to the conversation history, and send the next request", correct: true },
      { letter: "B", text: "Return the tool request to the user and end the loop", correct: false },
      { letter: "C", text: "Handle it as an application-specific edge case, like `max_tokens` or `stop_sequence`", correct: false },
      { letter: "D", text: "Re-send the same request unchanged until the model emits `end_turn`", correct: false },
    ],
    correct: "A",
    explanation: "`tool_use` means the model is requesting tool execution: run the tool(s), append the `tool_result` block(s) to history, and go back to step 1 of the loop. Other values like `max_tokens` and `stop_sequence` are the ones handled as application-specific cases.",
  },
  {
    id: "t-aa-18",
    domain: "agent-architecture",
    question: "Why does parsing assistant text for words like \"done\" or \"completed\" fail as a loop-termination check?",
    options: [
      { letter: "A", text: "The model never uses those words in its responses", correct: false },
      { letter: "B", text: "Text parsing works reliably but is slower than checking `stop_reason`", correct: false },
      { letter: "C", text: "Those words only ever appear once `stop_reason` is already `end_turn`", correct: false },
      { letter: "D", text: "The model can say \"I've completed step 1 of 3\" — text matching cannot distinguish sub-task completion from task completion, and phrasing varies across runs", correct: true },
    ],
    correct: "D",
    explanation: "Completion-word matching cannot tell sub-task completion apart from task completion, and phrasing is not stable across runs. Stopping on expressed confidence or positive sentiment fails for the same reason: self-assessed confidence is not calibrated to actual correctness.",
  },
  {
    id: "t-aa-19",
    domain: "agent-architecture",
    question: "In an `AgentDefinition`, what is true of the `system_prompt` field?",
    options: [
      { letter: "A", text: "It is re-negotiated with the coordinator on every turn of the subagent's task", correct: false },
      { letter: "B", text: "It sets the subagent's role, constraints, and behavioral rules, and is loaded once per subagent invocation — not re-negotiated mid-task", correct: true },
      { letter: "C", text: "It is the field a coordinator's routing logic reads to decide whether to delegate", correct: false },
      { letter: "D", text: "It doubles as the unique identifier used for routing and logging", correct: false },
    ],
    correct: "B",
    explanation: "`system_prompt` carries the subagent's role, constraints, and behavioral rules and is loaded once per invocation. The routing input a coordinator reads is `description`, and the unique routing/logging identifier is `name`.",
  },
  {
    id: "t-aa-20",
    domain: "agent-architecture",
    question: "What failure mode can a system-prompt instruction like \"always verify the customer's identity before helping them\" cause?",
    options: [
      { letter: "A", text: "It creates an unintended tool association, causing the model to call `get_customer` on every turn — including turns where identity was already verified", correct: true },
      { letter: "B", text: "It disables the `get_customer` tool for the rest of the conversation", correct: false },
      { letter: "C", text: "It forces the coordinator to route every request to an identity subagent", correct: false },
      { letter: "D", text: "None — only `allowed_tools` influences which tools get called", correct: false },
    ],
    correct: "A",
    explanation: "Imprecise wording creates a strong, repeated association between \"helping\" and \"verifying,\" producing redundant `get_customer` calls. Precise, scoped instructions — \"verify identity once per conversation, before the first account-modifying action\" — avoid this crosstalk.",
  },
  {
    id: "t-aa-21",
    domain: "agent-architecture",
    question: "In hub-and-spoke orchestration, which statement correctly describes the coordinator's role?",
    options: [
      { letter: "A", text: "It executes every tool itself and uses subagents only for logging", correct: false },
      { letter: "B", text: "It hands the user off to the most relevant subagent, which then converses with the user directly", correct: false },
      { letter: "C", text: "It decomposes requests, selects and delegates to subagents, aggregates results, handles surfaced errors, tracks state, and serves as the sole user-facing interface", correct: true },
      { letter: "D", text: "It supervises subagents that exchange results with each other directly over spoke-to-spoke edges", correct: false },
    ],
    correct: "C",
    explanation: "The star topology has no spoke-to-spoke edges: the user never talks to a subagent, and no subagent messages another directly. Routing all communication through the coordinator gives it the observability to notice gaps, apply consistent error handling, and control what information flows where.",
  },
  {
    id: "t-aa-22",
    domain: "agent-architecture",
    question: "Which set of elements does a well-formed `Task` prompt specify?",
    options: [
      { letter: "A", text: "A topic sentence plus a pointer to where the subagent can fetch the coordinator's conversation history", correct: false },
      { letter: "B", text: "Explicit goal, full inlined data context, output format, edge-case handling, and quality criteria", correct: true },
      { letter: "C", text: "The subagent's `allowed_tools` list and its `max_iterations` backstop", correct: false },
      { letter: "D", text: "Only the goal — additional context dilutes the subagent's attention", correct: false },
    ],
    correct: "B",
    explanation: "Because the subagent cannot go fetch what the coordinator already knows, every needed fact must be inlined alongside an explicit goal, a deterministically parseable output format, edge-case handling (e.g., \"if data is missing, don't guess\"), and quality criteria so the subagent doesn't have to infer what \"good\" looks like.",
  },
  {
    id: "t-aa-23",
    domain: "agent-architecture",
    question: "What does \"dynamic selection\" mean for a coordinator handling an incoming request?",
    options: [
      { letter: "A", text: "Randomizing which subagent handles each subtask to balance load", correct: false },
      { letter: "B", text: "Letting each subagent decide at runtime whether the request is relevant to it", correct: false },
      { letter: "C", text: "Choosing the subagents' tools dynamically based on the request", correct: false },
      { letter: "D", text: "Analyzing the request and invoking only the subagents it actually needs, rather than always routing through the full pipeline", correct: true },
    ],
    correct: "D",
    explanation: "A coordinator should not blindly run every subagent on every request — a simple factual lookup shouldn't wake the entire fleet. Dynamic selection is one of the three skills that separate a robust orchestrator from a naive pipeline, alongside scope partitioning and iterative refinement.",
  },
  {
    id: "t-aa-24",
    domain: "agent-architecture",
    question: "When a coordinator fans a task out to multiple subagents, what does scope partitioning require?",
    options: [
      { letter: "A", text: "Assigning each subagent a distinct slice — different subtopics or source types — so their work doesn't overlap and duplicate effort", correct: true },
      { letter: "B", text: "Giving every subagent the identical prompt so their results can be cross-validated", correct: false },
      { letter: "C", text: "Splitting the token budget evenly across all subagents", correct: false },
      { letter: "D", text: "Partitioning `allowed_tools` so that no two subagents share a tool", correct: false },
    ],
    correct: "A",
    explanation: "Scope partitioning means each fanned-out subagent gets a distinct slice of the work — different subtopics or source types — so effort isn't duplicated across overlapping assignments.",
  },
  {
    id: "t-aa-25",
    domain: "agent-architecture",
    question: "In an iterative refinement loop, what does the coordinator do after the synthesis step?",
    options: [
      { letter: "A", text: "Returns the synthesis immediately — re-invoking subagents would contaminate their isolated contexts", correct: false },
      { letter: "B", text: "Evaluates the result for coverage gaps, re-delegates targeted follow-up queries, and re-invokes synthesis — repeating until coverage is sufficient", correct: true },
      { letter: "C", text: "Asks each subagent to self-rate its confidence and retries any that score below a threshold", correct: false },
      { letter: "D", text: "Restarts the entire pipeline from scratch with a larger subagent fleet", correct: false },
    ],
    correct: "B",
    explanation: "A single decomposition pass often misses whole sub-areas — the classic failure decomposes \"creative industries\" into only visual-arts subtasks and never covers music, writing, or film, while every subagent still reports success on its narrow task. The coordinator must check for coverage gaps, re-delegate, and re-synthesize until they close.",
  },
  {
    id: "t-aa-26",
    domain: "agent-architecture",
    question: "What is `fork_session` for?",
    options: [
      { letter: "A", text: "Continuing a specific named prior conversation where it left off", correct: false },
      { letter: "B", text: "Compressing a long session into a compact structured summary", correct: false },
      { letter: "C", text: "Branching from a shared analysis baseline into independent lines of work, without either branch's context contaminating the other", correct: true },
      { letter: "D", text: "Running two subagents in parallel inside the same session context", correct: false },
    ],
    correct: "C",
    explanation: "`fork_session` branches from a shared baseline — e.g., exploring two refactoring or testing strategies from the same codebase analysis — with neither branch contaminating the other. Continuing a specific prior conversation is `--resume <session-name>`, which is why investigation sessions should be named deliberately.",
  },
  {
    id: "t-aa-27",
    domain: "agent-architecture",
    question: "If files were modified after a session's analysis, what should you do when resuming that session?",
    options: [
      { letter: "A", text: "Nothing — the agent automatically re-reads all files on resume", correct: false },
      { letter: "B", text: "Delete the session's prior tool results so nothing stale remains in context", correct: false },
      { letter: "C", text: "Raise the context window so both old and new file versions fit", correct: false },
      { letter: "D", text: "Explicitly inform the agent of the specific changes so it re-analyzes just those files", correct: true },
    ],
    correct: "D",
    explanation: "Telling the resumed session exactly what changed lets it re-analyze only the affected files. Otherwise it either trusts stale reads as current or is forced to re-explore the whole codebase.",
  },
  {
    id: "t-aa-28",
    domain: "agent-architecture",
    question: "What is the fundamental enforcement difference between prompt instructions and hooks?",
    options: [
      { letter: "A", text: "Prompt instructions are deterministic, while hooks depend on the model choosing to comply", correct: false },
      { letter: "B", text: "Prompt instructions are probabilistic with a non-zero failure rate however well-written; hooks live in application code outside the model's control and enforce rules with 100% determinism", correct: true },
      { letter: "C", text: "Hooks are only more reliable for models below a certain capability level", correct: false },
      { letter: "D", text: "There is no enforcement difference — hooks are simply easier to maintain than prompt text", correct: false },
    ],
    correct: "B",
    explanation: "A model can in principle talk its way around a prompt rule via edge cases, adversarial input, or drift, but a hook runs regardless of model reasoning. A system prompt saying \"never approve refunds over $500\" is good hygiene, not a control — the `PreToolUse` hook that mechanically blocks the call is the control.",
  },
  {
    id: "t-aa-29",
    domain: "agent-architecture",
    question: "When does the `PostToolUse` hook run, and what is it for?",
    options: [
      { letter: "A", text: "After a tool call returns, before the result is appended to history — it can normalize or trim the result before the model ever sees it", correct: true },
      { letter: "B", text: "After the model's final response, to audit the whole conversation", correct: false },
      { letter: "C", text: "Before a tool call executes, to block or redirect it", correct: false },
      { letter: "D", text: "After each user turn, to inject updated system-prompt rules", correct: false },
    ],
    correct: "A",
    explanation: "`PostToolUse` intercepts the tool result before it reaches the conversation history — for example, converting a raw Unix timestamp into ISO 8601 before the model reasons over it. Blocking or redirecting a call before execution is `PreToolUse`'s job.",
  },
  {
    id: "t-aa-30",
    domain: "agent-architecture",
    question: "Which advantages does the page attribute to a fixed pipeline (prompt chaining)?",
    options: [
      { letter: "A", text: "Its step order adapts to what earlier steps discover", correct: false },
      { letter: "B", text: "It eliminates the need for error handling between stages", correct: false },
      { letter: "C", text: "It handles open-ended investigation better than dynamic decomposition", correct: false },
      { letter: "D", text: "It is predictable, each stage is testable in isolation, runs are reproducible, and failure diagnosis is easy because you know exactly which stage broke", correct: true },
    ],
    correct: "D",
    explanation: "Fixed pipelines suit tasks whose shape is known in advance and repeatable, trading adaptability for predictability, per-stage testability, reproducibility, and easy failure diagnosis. Dynamic decomposition has lower reproducibility and harder diagnosis because the path itself may be the issue.",
  },
  {
    id: "t-aa-31",
    domain: "agent-architecture",
    question: "What is the correct response to a permission error (e.g., access denied, insufficient scope) inside a subagent?",
    options: [
      { letter: "A", text: "Retry with exponential backoff until access is granted", correct: false },
      { letter: "B", text: "Fix the input and resubmit the call", correct: false },
      { letter: "C", text: "Escalate — the subagent cannot resolve it itself", correct: true },
      { letter: "D", text: "Explain why the request is ineligible and propose an alternative path", correct: false },
    ],
    correct: "C",
    explanation: "Permission errors are not retryable and must be escalated. Fixing the input is the response to validation errors (blindly retrying the same bad input will fail again), and explaining plus proposing an alternative is the response to business errors like policy violations.",
  },
  {
    id: "t-aa-32",
    domain: "agent-architecture",
    question: "How should a subagent handle a transient failure before involving the coordinator?",
    options: [
      { letter: "A", text: "Propagate it immediately — only the coordinator has the context to decide on retries", correct: false },
      { letter: "B", text: "Attempt local recovery first — typically 1–2 retries with backoff — and propagate only errors it genuinely cannot resolve on its own", correct: true },
      { letter: "C", text: "Retry indefinitely until the call eventually succeeds", correct: false },
      { letter: "D", text: "Log it and return an empty result so the workflow continues", correct: false },
    ],
    correct: "B",
    explanation: "Local recovery (1–2 retries with backoff) keeps the coordinator from being flooded with noise it can't act on and keeps recoverable blips from becoming workflow-level failures. Validation and permission errors, by contrast, are not retryable locally and propagate immediately with their category.",
  },
  {
    id: "t-aa-33",
    domain: "agent-architecture",
    question: "What does the `attempted_query` field in a structured error response preserve?",
    options: [
      { letter: "A", text: "What was actually tried, so the coordinator or a human can distinguish \"this genuinely returned nothing\" from \"this failed before it could search\"", correct: true },
      { letter: "B", text: "The retry schedule the subagent will follow next", correct: false },
      { letter: "C", text: "The subagent's system prompt at the moment of failure", correct: false },
      { letter: "D", text: "A cache key for deduplicating repeated queries", correct: false },
    ],
    correct: "A",
    explanation: "`attempted_query` records what was actually tried, separating an empty-but-real result from a call that failed before it could run. Alongside it, `isError` and `errorCategory` let the coordinator branch on category (retry vs. escalate vs. explain) instead of string-matching error text.",
  },
  {
    id: "t-aa-34",
    domain: "agent-architecture",
    question: "Why should a failing subagent include `partial_results`, `completion_rate`, and `failed_sections` in its error response?",
    options: [
      { letter: "A", text: "So the coordinator can bill only for the completed portion of the task", correct: false },
      { letter: "B", text: "Because the SDK rejects error responses that omit them", correct: false },
      { letter: "C", text: "So retries can skip the transient-error classification step", correct: false },
      { letter: "D", text: "A subagent that got 3 of 5 things done should return the 3, not discard them — the coverage annotations tell the coordinator exactly how much to trust the result and what's missing", correct: true },
    ],
    correct: "D",
    explanation: "Partial results should never be thrown away just because the task as a whole didn't fully succeed. `completion_rate` and `failed_sections` tell the coordinator or downstream consumer precisely how much to trust the result and what remains uncovered.",
  },
  {
    id: "t-aa-35",
    domain: "agent-architecture",
    question: "If 4 of 5 parallel subtasks succeed, what should the workflow generally do?",
    options: [
      { letter: "A", text: "Abort entirely — partial results are unreliable by definition", correct: false },
      { letter: "B", text: "Retry all 5 subtasks so the results stay consistent with each other", correct: false },
      { letter: "C", text: "Return the 4 successful results with an annotated gap for the failed one", correct: true },
      { letter: "D", text: "Have the failed subagent return a plausible-looking success response so downstream consumers see a complete result", correct: false },
    ],
    correct: "C",
    explanation: "Aborting an entire workflow because one of several subtasks failed is an anti-pattern — return the successes with an annotated gap. Fabricating a plausible success is the \"hiding errors from the coordinator\" anti-pattern: it denies the coordinator the chance to route around the problem.",
  },
  {
    id: "t-aa-36",
    domain: "agent-architecture",
    question: "Which of the following is a legitimate trigger for escalating to a human?",
    options: [
      { letter: "A", text: "The model's self-rated confidence dropping below a threshold", correct: false },
      { letter: "B", text: "A genuine policy gap — the situation isn't covered by any rule the agent has", correct: true },
      { letter: "C", text: "A sentiment classifier detecting user frustration", correct: false },
      { letter: "D", text: "A generic classifier flagging the conversation as unusual", correct: false },
    ],
    correct: "B",
    explanation: "Legitimate triggers are an explicit user request (\"get me a manager\"), a genuine policy gap, repeated failed attempts at automated resolution, and a financial operation above a defined threshold — the same class of concern a `PreToolUse` hook enforces deterministically. Sentiment, self-rated confidence, and generic classifiers are unreliable proxies, just as they are for loop termination.",
  },
];
