import type { TheoryQuestion } from "@/domain/types";

export const contextReliabilityTheory: TheoryQuestion[] = [
  {
    id: "t-cr-01",
    domain: "context-reliability",
    question: "What must a client resend on every Claude API request to continue a conversation?",
    options: [
      { letter: "A", text: "Only the newest user message plus a session token issued by the API", correct: false },
      { letter: "B", text: "The system prompt and the most recent user/assistant exchange only", correct: false },
      { letter: "C", text: "The entire message history: system prompt, every prior user/assistant turn, every tool call, and every tool result", correct: true },
      { letter: "D", text: "A server-side conversation ID that the API uses to look up prior turns", correct: false },
    ],
    correct: "C",
    explanation: "The API is stateless — there is no server-side session or hidden conversation state, so the client resends the full history on every call. Anything that looks like persistent memory is an application-layer illusion: the harness re-injects it each turn.",
  },
  {
    id: "t-cr-02",
    domain: "context-reliability",
    question: "Which `stop_reason` value indicates the response was cut off mid-generation rather than finished?",
    options: [
      { letter: "A", text: "`end_turn`", correct: false },
      { letter: "B", text: "`max_tokens`", correct: true },
      { letter: "C", text: "`pause_turn`", correct: false },
      { letter: "D", text: "`stop_sequence`", correct: false },
    ],
    correct: "B",
    explanation: "`max_tokens` means the response was truncated, not finished — treating it as a complete answer is a common and avoidable reliability bug, so the caller must check `stop_reason` before trusting a response. `pause_turn` instead signals long-running server-side tool use (e.g. web search) paused for continuation, and `end_turn` is natural completion.",
  },
  {
    id: "t-cr-03",
    domain: "context-reliability",
    question: "What is the \"lost in the middle\" effect?",
    options: [
      { letter: "A", text: "Models process information at the start and end of a long input more reliably than information buried in the middle", correct: true },
      { letter: "B", text: "Tokens in the middle of the context window are evicted first when the token budget is exceeded", correct: false },
      { letter: "C", text: "Summarization steps drop the middle turns of a conversation while keeping the first and last", correct: false },
      { letter: "D", text: "The model loses track of the middle steps of a multi-step plan it generated itself", correct: false },
    ],
    correct: "A",
    explanation: "It is a structural property of long-context attention, not a training bug to route around with a clever prompt. It means *where* you place a fact matters as much as *whether* you include it — a constraint on line 400 of a 900-line tool result is at real risk of being ignored.",
  },
  {
    id: "t-cr-04",
    domain: "context-reliability",
    question: "Which component does the page identify as usually the largest, least controlled contributor to the context window and the fastest-growing part of an unmanaged long conversation?",
    options: [
      { letter: "A", text: "The system prompt", correct: false },
      { letter: "B", text: "Tool definitions (the JSON schema for every tool the model might call)", correct: false },
      { letter: "C", text: "Prior user/assistant message turns", correct: false },
      { letter: "D", text: "Tool results returned into the conversation", correct: true },
    ],
    correct: "D",
    explanation: "A single API call can return a multi-KB JSON blob when only two fields matter, and if never trimmed it sits in every subsequent request. Left unchecked, tool-result accumulation both wastes budget and worsens lost-in-the-middle by pushing earlier, still-relevant facts further into the middle.",
  },
  {
    id: "t-cr-05",
    domain: "context-reliability",
    question: "According to the page, how does degradation typically show up in a very long (extended) session?",
    options: [
      { letter: "A", text: "The API begins rejecting requests once the context window fills up", correct: false },
      { letter: "B", text: "The model gives inconsistent answers and drifts toward generic \"typical patterns\" instead of the specific classes, functions, and facts it discovered earlier", correct: true },
      { letter: "C", text: "Response latency grows every turn until the session times out", correct: false },
      { letter: "D", text: "The model refuses to call tools it used successfully earlier in the session", correct: false },
    ],
    correct: "B",
    explanation: "The tell is an agent that was precise at turn 10 answering at turn 60 as if reasoning from training priors rather than from what it actually found. Persistence techniques counter this by re-grounding the model in concrete findings instead of trusting them to survive in live context.",
  },
  {
    id: "t-cr-06",
    domain: "context-reliability",
    question: "Which technique does the page present as the core fix for summarization-driven precision loss (e.g. \"42.3%\" drifting to \"about 42%\")?",
    options: [
      { letter: "A", text: "A persistent case-facts block that lives outside the summarization path and is injected verbatim into every prompt", correct: true },
      { letter: "B", text: "A `PostToolUse` hook that strips verbose fields from tool results", correct: false },
      { letter: "C", text: "Instructing the summarizer to keep all numbers and dates exact", correct: false },
      { letter: "D", text: "Placing exact figures at the top of the prompt so they survive compaction", correct: false },
    ],
    correct: "A",
    explanation: "Because the block is never summarized — it is regenerated or carried forward verbatim regardless of how much the conversation is compacted — \"$89.99\" stays \"$89.99\" at turn 50 just as at turn 1. The drift is dangerous because the degraded value still looks confident and specific; the vagueness is quietly introduced, not flagged.",
  },
  {
    id: "t-cr-07",
    domain: "context-reliability",
    question: "What does a `PostToolUse` trimming hook do?",
    options: [
      { letter: "A", text: "Summarizes the whole conversation history after every tool call", correct: false },
      { letter: "B", text: "Deletes the oldest user turns once the context budget is exceeded", correct: false },
      { letter: "C", text: "Intercepts a tool's raw output before it is added to context and keeps only the fields that matter", correct: true },
      { letter: "D", text: "Compresses tool JSON schemas so tool definitions cost fewer tokens", correct: false },
    ],
    correct: "C",
    explanation: "This directly targets tool-result accumulation: a 5 KB raw response can become ~200 bytes. The saving compounds every subsequent turn because the trimmed result — not the raw one — is what gets resent.",
  },
  {
    id: "t-cr-08",
    domain: "context-reliability",
    question: "In position-aware placement, how does the page say injected content should be arranged?",
    options: [
      { letter: "A", text: "Chronologically, in the order the facts were encountered", correct: false },
      { letter: "B", text: "Action items at the top, key findings at the bottom, detail in between", correct: false },
      { letter: "C", text: "All critical facts clustered in the middle, where the model naturally focuses", correct: false },
      { letter: "D", text: "Key findings at the top, full supporting detail in the middle, action items / next steps at the bottom", correct: true },
    ],
    correct: "D",
    explanation: "This counters lost-in-the-middle by construction: the parts most likely to be skimmed or missed (the middle) are exactly the parts that matter least for the immediate decision, while recency at the bottom aids retrieval of next steps.",
  },
  {
    id: "t-cr-09",
    domain: "context-reliability",
    question: "Which escalation trigger does the page classify as reliable?",
    options: [
      { letter: "A", text: "Sentiment analysis detecting an angry customer", correct: false },
      { letter: "B", text: "The model's self-rated confidence dropping below a threshold", correct: false },
      { letter: "C", text: "An automatic complexity classifier scoring the case as hard", correct: false },
      { letter: "D", text: "No progress after N attempts", correct: true },
    ],
    correct: "D",
    explanation: "No progress after N attempts is concrete, measurable evidence the current approach isn't working; the other reliable triggers are an explicit human request, policy silence, a financial op over a policy threshold, and multiple lookup matches. Sentiment doesn't correlate with case complexity, self-rated confidence isn't a calibrated probability, and an unlabeled complexity classifier just hides guessing behind an objective-looking number.",
  },
  {
    id: "t-cr-10",
    domain: "context-reliability",
    question: "For a frustrated customer who has not explicitly asked for a human, which escalation pattern does the page prescribe?",
    options: [
      { letter: "A", text: "Acknowledge the issue, offer a concrete resolution, and escalate only if the customer insists again after that offer", correct: true },
      { letter: "B", text: "Escalate immediately at the first sign of frustration", correct: false },
      { letter: "C", text: "Run sentiment analysis and escalate once anger crosses a threshold", correct: false },
      { letter: "D", text: "Attempt the fix repeatedly and never escalate unless policy is silent", correct: false },
    ],
    correct: "A",
    explanation: "Escalating at the first hint of frustration overloads human queues and trains customers that frustration is the fastest path to a human. The other two patterns are immediate escalation (reserved for an explicit human request) and attempt-then-escalate (for a plausibly solvable issue: try the fix, verify, escalate only if it doesn't resolve the case).",
  },
  {
    id: "t-cr-11",
    domain: "context-reliability",
    question: "What standard must a structured escalation handoff meet?",
    options: [
      { letter: "A", text: "It should attach the full conversation transcript so nothing is lost", correct: false },
      { letter: "B", text: "It should contain only the customer ID and a link to the conversation", correct: false },
      { letter: "C", text: "The human must be able to act without reading the full transcript, using fields like `actions_taken`, `root_cause`, `recommended_action`, and `escalation_reason`", correct: true },
      { letter: "D", text: "It should include a sentiment score and a priority ranking for triage", correct: false },
    ],
    correct: "C",
    explanation: "The handoff is a structured payload, not \"here's the conversation, good luck.\" Every field answers a question the human would otherwise reconstruct from the transcript: what happened, what's been tried, why it wasn't enough, and what to do next.",
  },
  {
    id: "t-cr-12",
    domain: "context-reliability",
    question: "A system reports 97% overall accuracy but fails 40% of the time on one rare document type. What fix does the page recommend?",
    options: [
      { letter: "A", text: "Raise the single system-wide accuracy threshold until the failures disappear", correct: false },
      { letter: "B", text: "Stratified sampling: audit accuracy by segment and set per-segment thresholds using field-level confidence scores", correct: true },
      { letter: "C", text: "Retrain the model on more examples of the rare document type", correct: false },
      { letter: "D", text: "Average accuracy across document types, weighted by volume", correct: false },
    ],
    correct: "B",
    explanation: "Aggregate accuracy hides pattern-specific failure when the failing segment is too small a share to move the blended number. Auditing by segment (document type, field, customer tier, language) surfaces hidden pockets of failure, and a historically weak segment gets a stricter auto-processing threshold even if the overall number looks healthy.",
  },
  {
    id: "t-cr-13",
    domain: "context-reliability",
    question: "Two sources report different values for the same metric (e.g. 10% in a 2023 publication, 15% in a 2024 one). How should the aggregation step handle this?",
    options: [
      { letter: "A", text: "Average the two values so downstream consumers get a single number", correct: false },
      { letter: "B", text: "Preserve both values with their attribution (including `publication_date`) and set a `conflict_detected` flag", correct: true },
      { letter: "C", text: "Keep only the more recent value and silently discard the older one", correct: false },
      { letter: "D", text: "Strip the dates and report the range 10-15%", correct: false },
    ],
    correct: "B",
    explanation: "Averaging destroys information and can produce a value neither source reported; the `conflict_detected` flag prevents the aggregation step from silently making the trust call, pushing it to the coordinator or end user who has more context. Preserved dates matter too: 10% (2023) vs 15% (2024) is very likely growth over time, not a contradiction — claim-source mapping keeps `source_url`, `source_name`, `publication_date`, and `confidence` alongside each claim.",
  },
  {
    id: "t-cr-14",
    domain: "context-reliability",
    question: "How does the page say the output format should be chosen when rendering synthesized findings?",
    options: [
      { letter: "A", text: "By content type: tables for numeric/comparable data, prose for narrative explanation, lists for action items", correct: true },
      { letter: "B", text: "Always prose, since it reads most naturally for humans", correct: false },
      { letter: "C", text: "Always tables, since structure survives summarization best", correct: false },
      { letter: "D", text: "Whatever format minimizes total token count", correct: false },
    ],
    correct: "A",
    explanation: "Forcing everything into prose buries numbers exactly where lost-in-the-middle and summarization drift do the most damage, while forcing narrative into a table strips the nuance a reader needs to interpret it correctly.",
  },
  {
    id: "t-cr-15",
    domain: "context-reliability",
    question: "Per the page's mapping of the six context-management techniques to what they counter, which pairing is correct?",
    options: [
      { letter: "A", text: "Case-facts block → crash recovery", correct: false },
      { letter: "B", text: "Position-aware placement → summarization precision loss", correct: false },
      { letter: "C", text: "Subagent delegation → isolating verbose discovery so raw dumps never enter the parent's context", correct: true },
      { letter: "D", text: "Scratchpad files → tool-result bloat", correct: false },
    ],
    correct: "C",
    explanation: "The subagent burns its *own* context budget on noisy exploration and returns only a distilled summary (~2 sentences, not 400 lines). The full mapping: case-facts block → precision loss, trimming hooks → tool-result bloat, position-aware placement → lost-in-the-middle, scratchpads → cross-session persistence, subagent delegation → verbose discovery, structured state + manifest → crash recovery (resume from `completed_phases`).",
  },
  {
    id: "t-cr-16",
    domain: "context-reliability",
    question: "What is the first consequence the page draws from the API's statelessness?",
    options: [
      { letter: "A", text: "Latency stays constant because the server caches the conversation between calls", correct: false },
      { letter: "B", text: "Cost and latency scale with history length, since every turn re-sends and re-processes everything that came before", correct: true },
      { letter: "C", text: "Cost depends only on the newest message, because prior turns are billed once", correct: false },
      { letter: "D", text: "Latency grows only on turns that include tool calls", correct: false },
    ],
    correct: "B",
    explanation: "Because the full history is re-processed on every request, unbounded history growth is a real production problem, not a theoretical one — and it is why prompt caching exists. The second consequence is that \"memory\" is an application-layer illusion: the harness re-injects it each call; the model isn't remembering.",
  },
  {
    id: "t-cr-17",
    domain: "context-reliability",
    question: "Which four components does the page list as sharing the context window's fixed token budget in a single request?",
    options: [
      { letter: "A", text: "System prompt, tool definitions, message history, and tool results", correct: true },
      { letter: "B", text: "System prompt, model weights, message history, and output tokens", correct: false },
      { letter: "C", text: "Tool definitions, embeddings, message history, and stop sequences", correct: false },
      { letter: "D", text: "System prompt, message history, sampling parameters, and tool results", correct: false },
    ],
    correct: "A",
    explanation: "Tool definitions cost the full JSON schema of every tool the model *might* call, whether or not it is used that turn, and the system prompt is sent every turn. Tool results are usually the largest and least controlled contributor to the budget.",
  },
  {
    id: "t-cr-18",
    domain: "context-reliability",
    question: "Which `stop_reason` value signals that long-running server-side tool use (e.g. web search) has paused for continuation?",
    options: [
      { letter: "A", text: "`tool_use`", correct: false },
      { letter: "B", text: "`stop_sequence`", correct: false },
      { letter: "C", text: "`end_turn`", correct: false },
      { letter: "D", text: "`pause_turn`", correct: true },
    ],
    correct: "D",
    explanation: "`pause_turn` means a long-running server-side tool paused and the turn should be continued. `tool_use` instead means the model wants to call a tool and is pausing for the result, and `end_turn` is natural completion.",
  },
  {
    id: "t-cr-19",
    domain: "context-reliability",
    question: "What does a `stop_reason` of `tool_use` mean?",
    options: [
      { letter: "A", text: "The response hit the token limit while emitting a tool call", correct: false },
      { letter: "B", text: "A server-side tool is still running and the turn is paused", correct: false },
      { letter: "C", text: "The model wants to call a tool and is pausing for the result", correct: true },
      { letter: "D", text: "The model finished its turn after a tool result was returned", correct: false },
    ],
    correct: "C",
    explanation: "`tool_use` is the model requesting a tool invocation and waiting for the caller to return the result. The full set of values discussed is `end_turn` (natural completion), `max_tokens` (truncated), `stop_sequence`, `tool_use`, and `pause_turn` (long-running server-side tool use paused for continuation).",
  },
  {
    id: "t-cr-20",
    domain: "context-reliability",
    question: "When history is compacted by summarization, what does the page say survives well and what degrades?",
    options: [
      { letter: "A", text: "Qualitative narrative survives well, but numeric precision does not — exact figures and dates drift into vague approximations", correct: true },
      { letter: "B", text: "Numbers survive well, but narrative context is dropped first", correct: false },
      { letter: "C", text: "Everything degrades uniformly in proportion to the compression ratio", correct: false },
      { letter: "D", text: "Only the earliest turns degrade; recent content is preserved verbatim", correct: false },
    ],
    correct: "A",
    explanation: "\"42.3%\" tends to drift into \"about 42%\" and \"2024-06-15\" into \"sometime last year\" after a round or two of summarization. This is dangerous because the degraded value still looks confident and specific — the vagueness is quietly introduced, never flagged.",
  },
  {
    id: "t-cr-21",
    domain: "context-reliability",
    question: "What is the purpose of scratchpad files as a context management technique?",
    options: [
      { letter: "A", text: "They cache tool definitions so schemas are not resent every turn", correct: false },
      { letter: "B", text: "They store the full conversation transcript for compliance auditing", correct: false },
      { letter: "C", text: "They hold intermediate reasoning so the model can replay it within the same turn", correct: false },
      { letter: "D", text: "They persist key findings to disk so a fresh session or subagent can read a small targeted file instead of needing the full prior transcript re-sent", correct: true },
    ],
    correct: "D",
    explanation: "Scratchpads serve work that spans sessions or exceeds a single context window, trading a large amount of conversation history for a small, targeted file read. They also counter extended-session degradation by re-grounding the model in concrete findings.",
  },
  {
    id: "t-cr-22",
    domain: "context-reliability",
    question: "In the structured state persistence pattern, how does a new agent resume after a crash or interruption?",
    options: [
      { letter: "A", text: "It replays the full event log from the beginning of the workflow", correct: false },
      { letter: "B", text: "It reads the manifest, loads each agent's state file from the known disk location, and resumes from `completed_phases` instead of restarting the whole workflow", correct: true },
      { letter: "C", text: "It asks the user to summarize what had been done so far", correct: false },
      { letter: "D", text: "It restores an in-memory snapshot from the API's session store", correct: false },
    ],
    correct: "B",
    explanation: "State is persisted to a known location on disk — a per-agent state file plus a manifest that indexes all of them — rather than only in memory. Resuming from `completed_phases` avoids redoing finished work.",
  },
  {
    id: "t-cr-23",
    domain: "context-reliability",
    question: "What role does the `coverage_gaps` field in an agent's state file play later in the workflow?",
    options: [
      { letter: "A", text: "It lists tools the agent was denied permission to use", correct: false },
      { letter: "B", text: "It tracks which context-management techniques were applied", correct: false },
      { letter: "C", text: "It feeds honest, caveated reporting instead of the workflow silently pretending the work was complete", correct: true },
      { letter: "D", text: "It records which turns were dropped during summarization", correct: false },
    ],
    correct: "C",
    explanation: "An entry like \"No data for region EU-WEST after 2025-06-20\" persists what the agent knows it did not cover, so downstream reporting can state its limits explicitly rather than presenting partial work as complete.",
  },
  {
    id: "t-cr-24",
    domain: "context-reliability",
    question: "Per the reliable-triggers table, how should an agent handle multiple lookup matches?",
    options: [
      { letter: "A", text: "Resolve the ambiguity with a clarifying question first, and escalate only if the clarifier itself fails", correct: true },
      { letter: "B", text: "Escalate immediately, since ambiguity is unresolvable by the agent", correct: false },
      { letter: "C", text: "Pick the most recent match and proceed", correct: false },
      { letter: "D", text: "Merge the matching records and continue with the combined data", correct: false },
    ],
    correct: "A",
    explanation: "Multiple matches is the one reliable trigger with a step before escalation: ambiguity should be resolved with a clarifying question first, and escalated only if that clarifier fails.",
  },
  {
    id: "t-cr-25",
    domain: "context-reliability",
    question: "Why is \"policy is silent on the request\" a reliable escalation trigger?",
    options: [
      { letter: "A", text: "Because silent policies always indicate legal risk", correct: false },
      { letter: "B", text: "Because customers are most frustrated by policy gaps", correct: false },
      { letter: "C", text: "Because it forces the complexity classifier to abstain", correct: false },
      { letter: "D", text: "Because the agent has no authorized action to take, and guessing is worse than asking", correct: true },
    ],
    correct: "D",
    explanation: "Like the other reliable triggers, it is objective rather than a judgment call — a financial op over a policy threshold is reliable for the same reason: it is an objective, pre-agreed dollar/risk boundary.",
  },
  {
    id: "t-cr-26",
    domain: "context-reliability",
    question: "Why does the page classify an automatic complexity classifier as an unreliable escalation trigger?",
    options: [
      { letter: "A", text: "It adds too much latency to each response", correct: false },
      { letter: "B", text: "Without a labeled training set matched to your actual case distribution, it is guessing too — it just hides that guessing behind a number that looks objective", correct: true },
      { letter: "C", text: "It can only score text, not tool results", correct: false },
      { letter: "D", text: "It always escalates more cases than sentiment analysis does", correct: false },
    ],
    correct: "B",
    explanation: "The same flaw runs through all three unreliable triggers: sentiment fails because customer mood does not correlate with case complexity, and self-rated confidence is not a calibrated probability. None of them track whether the case is solvable by policy, right now, by this agent — so escalations built on them don't correlate with real need.",
  },
  {
    id: "t-cr-27",
    domain: "context-reliability",
    question: "What triggers the \"immediate\" escalation pattern, and what does the agent do first?",
    options: [
      { letter: "A", text: "A financial threshold breach; the agent retries the operation once before escalating", correct: false },
      { letter: "B", text: "Detected frustration; the agent apologizes and escalates", correct: false },
      { letter: "C", text: "An explicit human request; the agent escalates on the spot with no attempt to resolve first", correct: true },
      { letter: "D", text: "Policy silence; the agent asks a clarifying question before escalating", correct: false },
    ],
    correct: "C",
    explanation: "An explicit request for a human is unambiguous customer intent, so no further resolution attempts are made. The other two patterns are attempt-then-escalate and acknowledge → offer a concrete resolution → escalate only on reiterated insistence.",
  },
  {
    id: "t-cr-28",
    domain: "context-reliability",
    question: "For which situation is the attempt-then-escalate pattern intended, and what are its steps?",
    options: [
      { letter: "A", text: "Any financial operation: escalate first, then retry after approval", correct: false },
      { letter: "B", text: "Explicit human requests: attempt one fix before honoring the request", correct: false },
      { letter: "C", text: "Frustrated customers: attempt a fix silently before acknowledging the issue", correct: false },
      { letter: "D", text: "A plausibly solvable issue: try the fix, verify it, and only escalate if it doesn't resolve the case", correct: true },
    ],
    correct: "D",
    explanation: "Verification sits between the attempt and the escalation decision — the agent escalates only when the verified outcome shows the case is still unresolved, not merely because the fix was hard.",
  },
  {
    id: "t-cr-29",
    domain: "context-reliability",
    question: "What do field-level confidence scores enable when combined with stratified sampling?",
    options: [
      { letter: "A", text: "Per-segment thresholds for what gets auto-processed versus routed to human review, with stricter thresholds for historically weak segments", correct: true },
      { letter: "B", text: "A single calibrated system-wide accuracy number", correct: false },
      { letter: "C", text: "Automatic retraining on any segment that falls below the average", correct: false },
      { letter: "D", text: "Removing human review entirely once overall confidence exceeds 97%", correct: false },
    ],
    correct: "A",
    explanation: "A segment with historically weak performance gets a stricter auto-processing threshold even if the overall system-wide number looks healthy — the opposite of trusting a blended aggregate metric.",
  },
  {
    id: "t-cr-30",
    domain: "context-reliability",
    question: "Which fields does the page's claim-to-source mapping preserve alongside each claim?",
    options: [
      { letter: "A", text: "`source_url`, `retrieval_method`, `token_count`, and `model_version`", correct: false },
      { letter: "B", text: "`source_url`, `source_name`, `publication_date`, and `confidence`", correct: true },
      { letter: "C", text: "`source_name`, `sentiment`, `confidence`, and `conflict_detected`", correct: false },
      { letter: "D", text: "`claim_id`, `source_url`, `reviewer`, and `accuracy`", correct: false },
    ],
    correct: "B",
    explanation: "Together these let a downstream consumer — human or agent — judge how much weight to put on the claim without re-doing the research, preserved as structured data rather than a footnote in prose. Losing the link back to where a claim came from is a silent reliability failure: the output looks equally confident whether it is well-sourced or fabricated.",
  },
  {
    id: "t-cr-31",
    domain: "context-reliability",
    question: "Why does preserving `publication_date` change how conflicting values should be interpreted?",
    options: [
      { letter: "A", text: "Because newer sources are always more accurate and should win", correct: false },
      { letter: "B", text: "Because dates let the aggregator average the values weighted by recency", correct: false },
      { letter: "C", text: "Because a 2023 source reporting 10% and a 2024 source reporting 15% is very likely growth over time, not a contradiction — but only if the dates survive aggregation", correct: true },
      { letter: "D", text: "Because sources past a freshness cutoff must be dropped from the mapping", correct: false },
    ],
    correct: "C",
    explanation: "Strip the dates during aggregation and the same two numbers look like an unexplained inconsistency instead of a trend. `publication_date` is what distinguishes real contradictions from temporal trends.",
  },
];
