import type { TheoryQuestion } from "@/domain/types";

export const promptEngineeringTheory: TheoryQuestion[] = [
  {
    id: "t-pe-01",
    domain: "prompt-engineering",
    question: "How many few-shot examples does the page recommend including in a prompt?",
    options: [
      { letter: "A", text: "Exactly 1, to keep the prompt as short as possible", correct: false },
      { letter: "B", text: "2-4 targeted examples, each teaching a different edge case", correct: true },
      { letter: "C", text: "5-10, one per output field", correct: false },
      { letter: "D", text: "As many as the context window allows, since more examples always improve accuracy", correct: false },
    ],
    correct: "B",
    explanation: "More examples add tokens without adding new decision boundaries. The page recommends 2-4 targeted examples, picking ones that each teach a different edge case rather than restating the same one.",
  },
  {
    id: "t-pe-02",
    domain: "prompt-engineering",
    question: "Which of the following is NOT one of the five example types the page says consistently earn their tokens?",
    options: [
      { letter: "A", text: "Ambiguous tool selection, showing the reasoning behind the call", correct: false },
      { letter: "B", text: "Acceptable vs. problematic code pairs that teach the boundary", correct: false },
      { letter: "C", text: "Informal measurements with a conversion example", correct: false },
      { letter: "D", text: "Chain-of-thought walkthroughs of multi-step arithmetic", correct: true },
    ],
    correct: "D",
    explanation: "The five types are ambiguous tool selection, output formatting, acceptable vs. problematic code, extraction across document formats, and informal measurements. Arithmetic chain-of-thought walkthroughs are not on the list.",
  },
  {
    id: "t-pe-03",
    domain: "prompt-engineering",
    question: "According to the page, what should replace vague qualifiers like \"be conservative\" or \"flag important issues\"?",
    options: [
      { letter: "A", text: "An enumerated allow/deny list paired with a severity rubric that gives each level a concrete example", correct: true },
      { letter: "B", text: "A confidence threshold the model must exceed before flagging", correct: false },
      { letter: "C", text: "A longer natural-language paragraph describing the desired attitude", correct: false },
      { letter: "D", text: "A lower temperature so the model interprets instructions more literally", correct: false },
    ],
    correct: "A",
    explanation: "Ambiguity in the instruction becomes ambiguity and drift in the output. Explicit \"Flag ONLY if / Do NOT flag\" criteria plus a severity rubric with a concrete example per level measurably reduce both drift and false positives.",
  },
  {
    id: "t-pe-04",
    domain: "prompt-engineering",
    question: "What does the page recommend when one finding category generates too many false positives to trust?",
    options: [
      { letter: "A", text: "Lower its severity to `LOW` so it is easier to ignore", correct: false },
      { letter: "B", text: "Ask the model to double-check that category before reporting it", correct: false },
      { letter: "C", text: "Temporarily disable the category while iterating on its criteria separately", correct: true },
      { letter: "D", text: "Keep reporting it, since removing a category reduces recall", correct: false },
    ],
    correct: "C",
    explanation: "A category that fires wrong most of the time erodes trust in the accurate categories beside it. Silencing it protects the signal of the rest until its prompt is fixed.",
  },
  {
    id: "t-pe-05",
    domain: "prompt-engineering",
    question: "For code review, what chaining structure does the page recommend?",
    options: [
      { letter: "A", text: "A single multi-file pass so cross-file bugs are never missed", correct: false },
      { letter: "B", text: "A per-file pass for local issues first, then a separate cross-file integration pass", correct: true },
      { letter: "C", text: "A cross-file pass first to establish context, then per-file cleanup", correct: false },
      { letter: "D", text: "Parallel passes over random file subsets, merged by a voting step", correct: false },
    ],
    correct: "B",
    explanation: "Each file gets full attention in the per-file pass; the cross-file pass then only examines how the already-identified pieces interact. A single multi-file pass suffers attention dilution, inconsistent flagging, and missed obvious bugs.",
  },
  {
    id: "t-pe-06",
    domain: "prompt-engineering",
    question: "What three things should a retry prompt include after a validation failure?",
    options: [
      { letter: "A", text: "The JSON Schema, the model's temperature, and a request to try again", correct: false },
      { letter: "B", text: "The failed extraction, an instruction to \"be careful,\" and a shortened version of the document", correct: false },
      { letter: "C", text: "The original source document, the previous (incorrect) extraction, and the specific error stated concretely", correct: true },
      { letter: "D", text: "The validation code, the stack trace, and the Pydantic model definition", correct: false },
    ],
    correct: "C",
    explanation: "A bare \"try again\" is not enough. A specific error like \"Field 'total' = 150, but sum(line_items) = 145\" lets the model localize the mistake instead of re-deriving the whole extraction from scratch.",
  },
  {
    id: "t-pe-07",
    domain: "prompt-engineering",
    question: "When is retry-with-feedback ineffective?",
    options: [
      { letter: "A", text: "When the error is a wrong type or a missing required field", correct: false },
      { letter: "B", text: "When a stated total does not match the sum of its line items", correct: false },
      { letter: "C", text: "When the validation is done with Pydantic instead of a plain JSON Schema", correct: false },
      { letter: "D", text: "When the information is absent from the source, or the model is confidently hallucinating a value", correct: true },
    ],
    correct: "D",
    explanation: "No amount of re-prompting invents a number that was never in the document, and \"check again\" does not help a model unaware it fabricated the value. The fix is to surface the field as `null`/`unclear` and route to a human.",
  },
  {
    id: "t-pe-08",
    domain: "prompt-engineering",
    question: "What are Pydantic's three roles in the validation loop?",
    options: [
      { letter: "A", text: "Prompt templating, response caching, and token counting", correct: false },
      { letter: "B", text: "Structural validation, custom validators for business logic, and JSON Schema generation for `tool_use`", correct: true },
      { letter: "C", text: "Type inference, database persistence, and API routing", correct: false },
      { letter: "D", text: "Retry orchestration, error logging, and schema migration", correct: false },
    ],
    correct: "B",
    explanation: "Pydantic checks types, required fields, and enums; expresses business rules a schema cannot (like `sum(line_items) == total`); and generates the JSON Schema for the `tool_use` definition, so the validation and generation contracts never drift apart.",
  },
  {
    id: "t-pe-09",
    domain: "prompt-engineering",
    question: "Which fields does the page's dual-value self-correction example extract for an invoice?",
    options: [
      { letter: "A", text: "`stated_total`, `calculated_total`, and `conflict_detected`", correct: true },
      { letter: "B", text: "`total`, `retry_count`, and `is_valid`", correct: false },
      { letter: "C", text: "`line_items`, `subtotal`, and `tax`", correct: false },
      { letter: "D", text: "`stated_total`, `expected_total`, and `error_message`", correct: false },
    ],
    correct: "A",
    explanation: "`stated_total` is read directly off the document, `calculated_total` is derived by summing the line items, and `conflict_detected` flips to `true` when they disagree — surfacing the discrepancy without a second round trip.",
  },
  {
    id: "t-pe-10",
    domain: "prompt-engineering",
    question: "What is the purpose of the `detected_pattern` field on each review finding?",
    options: [
      { letter: "A", text: "To let the model skip files that match known-safe patterns", correct: false },
      { letter: "B", text: "To store the regex used to locate the issue in the diff", correct: false },
      { letter: "C", text: "To record the severity rubric level assigned to the finding", correct: false },
      { letter: "D", text: "To name the code construct that triggered the finding, so dismissals reveal which patterns produce false positives", correct: true },
    ],
    correct: "D",
    explanation: "When a developer dismisses a finding, aggregating `detected_pattern` across dismissals turns scattered feedback into a systematic signal about which criteria to tighten, instead of guessing.",
  },
  {
    id: "t-pe-11",
    domain: "prompt-engineering",
    question: "Why does the page recommend adding \"other\" or \"unclear\" to an `enum` in an output schema?",
    options: [
      { letter: "A", text: "It gives the model a legitimate way to say a value does not fit the categories, instead of guessing the closest one", correct: true },
      { letter: "B", text: "It reduces token usage by shortening the enum list", correct: false },
      { letter: "C", text: "JSON Schema requires every enum to include a fallback value", correct: false },
      { letter: "D", text: "It lets the schema validator auto-correct mis-categorized values", correct: false },
    ],
    correct: "A",
    explanation: "The escape hatch prevents forced guessing; pair \"other\" with a free-text `*_detail` field for specifics. Similarly, nullable fields let genuinely absent information be `null` rather than fabricated to satisfy a required string.",
  },
  {
    id: "t-pe-12",
    domain: "prompt-engineering",
    question: "What does `tool_use` with a JSON Schema guarantee about the output?",
    options: [
      { letter: "A", text: "Both valid JSON syntax and semantic correctness of the values", correct: false },
      { letter: "B", text: "Valid syntax plus automatic normalization of dates and currencies", correct: false },
      { letter: "C", text: "Valid JSON syntax only — a schema-valid response can still be wrong, incomplete, or hallucinated", correct: true },
      { letter: "D", text: "Nothing enforceable; the schema is purely advisory", correct: false },
    ],
    correct: "C",
    explanation: "Syntax guarantees are a floor, not a substitute for the validation loop. Normalization rules (ISO 8601 dates, numeric amount plus ISO currency code, decimal fractions) belong in the prompt, since a schema constrains shape but not content conventions.",
  },
  {
    id: "t-pe-13",
    domain: "prompt-engineering",
    question: "Which statement about the Message Batches API is accurate?",
    options: [
      { letter: "A", text: "It guarantees results within one hour for batches under 1,000 items", correct: false },
      { letter: "B", text: "It is asynchronous, roughly 50% cheaper than the synchronous Messages API, and can take up to 24 hours with no guarantee of finishing sooner", correct: true },
      { letter: "C", text: "It supports multi-turn tool-use loops within each batch entry", correct: false },
      { letter: "D", text: "A batch fails atomically — if one item errors, the whole batch must be resubmitted", correct: false },
    ],
    correct: "B",
    explanation: "Each entry is single request -> single response, correlated to its result by `custom_id` (the only reliable join key). Partial failures are handled by resubmitting only the failed entries as a smaller batch, and prompts should be refined on a small sample before committing a large run.",
  },
  {
    id: "t-pe-14",
    domain: "prompt-engineering",
    question: "If results are due in 30 hours and a batch can take up to 24 hours to process, when must the batch be submitted?",
    options: [
      { letter: "A", text: "Within the first 6 hours — `submission_deadline = final_deadline - 24h`", correct: true },
      { letter: "B", text: "Any time in the first 24 hours, since batches usually finish early", correct: false },
      { letter: "C", text: "Within the first 12 hours, to leave a margin for one full retry", correct: false },
      { letter: "D", text: "Immediately at hour zero; any later submission violates the SLA", correct: false },
    ],
    correct: "A",
    explanation: "Work backward from the deadline by subtracting the 24-hour processing ceiling. The Batches API gives no latency guarantee below that ceiling, so cutting it closer risks missing the deadline with no recourse.",
  },
  {
    id: "t-pe-15",
    domain: "prompt-engineering",
    question: "According to the interview pattern, what should Claude do before committing to an implementation?",
    options: [
      { letter: "A", text: "Generate three alternative implementations and let the user pick one", correct: false },
      { letter: "B", text: "Write tests first so the requirements emerge from the test suite", correct: false },
      { letter: "C", text: "Proceed with the most common industry default and list assumptions at the end", correct: false },
      { letter: "D", text: "Ask clarifying questions to surface non-obvious design decisions before building", correct: true },
    ],
    correct: "D",
    explanation: "Asking first is cheaper than building the wrong thing and reworking it, and the questions document the design's assumptions. It is worth it in unfamiliar domains, tasks with non-obvious implications, and when multiple viable approaches depend on context not given.",
  },
  {
    id: "t-pe-16",
    domain: "prompt-engineering",
    question: "Why do 2-4 targeted examples usually outperform another paragraph of description?",
    options: [
      { letter: "A", text: "Examples always consume fewer tokens than equivalent prose", correct: false },
      { letter: "B", text: "Models are trained to weight examples more heavily than instructions", correct: false },
      { letter: "C", text: "An example unambiguously shows both the expected format and the decision logic behind it, while a vague instruction can be interpreted many different ways", correct: true },
      { letter: "D", text: "Examples let the model skip reading the rest of the system prompt", correct: false },
    ],
    correct: "C",
    explanation: "A vague instruction like \"be more precise\" or \"be conservative\" can be interpreted many different ways. An example encodes the format and the decision logic that a rule can't fully spell out.",
  },
  {
    id: "t-pe-17",
    domain: "prompt-engineering",
    question: "For which kinds of input does the page say few-shot prompting is especially strong?",
    options: [
      { letter: "A", text: "Informal or highly varied inputs like free-text tickets, hand-written measurements, and mixed document formats", correct: true },
      { letter: "B", text: "Strictly formatted, machine-generated logs with a fixed grammar", correct: false },
      { letter: "C", text: "Short yes/no classification tasks with binary answers", correct: false },
      { letter: "D", text: "Inputs that have already been validated against a JSON Schema", correct: false },
    ],
    correct: "A",
    explanation: "A rule can't enumerate every variant of informal input, but a handful of representative examples lets the model generalize past the surface variation.",
  },
  {
    id: "t-pe-18",
    domain: "prompt-engineering",
    question: "In the ambiguous tool selection example type, what should each example show?",
    options: [
      { letter: "A", text: "Every available tool's full JSON signature", correct: false },
      { letter: "B", text: "The same tool called with several different argument sets", correct: false },
      { letter: "C", text: "Only failing tool calls, so the model learns what to avoid", correct: false },
      { letter: "D", text: "The reasoning behind the choice, not just the call — e.g., an explicit escalation request goes straight to escalate_to_human with no lookup first", correct: true },
    ],
    correct: "D",
    explanation: "The page pairs a routine investigation (get_customer_context then lookup_order) with an explicit escalation request that skips lookup entirely — the examples teach the decision logic, not just which tools exist.",
  },
  {
    id: "t-pe-19",
    domain: "prompt-engineering",
    question: "According to the output formatting example type, what is the best way to teach an output format?",
    options: [
      { letter: "A", text: "A JSON Schema in the prompt with no example", correct: false },
      { letter: "B", text: "A complete worked example of the output, which beats a schema description alone", correct: true },
      { letter: "C", text: "A prose description of what each field means", correct: false },
      { letter: "D", text: "A regular expression the output must match", correct: false },
    ],
    correct: "B",
    explanation: "The page shows a fully populated finding object (location, issue, severity, suggested_fix) and states that a complete worked example beats a schema description alone.",
  },
  {
    id: "t-pe-20",
    domain: "prompt-engineering",
    question: "Why does the acceptable vs. problematic code example type pair a flagged case with a clean one?",
    options: [
      { letter: "A", text: "So the model learns the boundary between the two, not just the bad pattern", correct: true },
      { letter: "B", text: "To double the number of examples without adding tokens", correct: false },
      { letter: "C", text: "Because JSON Schemas require both positive and negative cases", correct: false },
      { letter: "D", text: "So the model can auto-generate fixes by diffing the two versions", correct: false },
    ],
    correct: "A",
    explanation: "The page flags loose equality (==) but explicitly shows strict equality (===) as \"do not flag\" — the pair teaches where the line sits instead of only what bad code looks like.",
  },
  {
    id: "t-pe-21",
    domain: "prompt-engineering",
    question: "What does the extraction-across-document-formats example type teach the model?",
    options: [
      { letter: "A", text: "To preserve the original formatting of each source in the output", correct: false },
      { letter: "B", text: "To prefer bibliography entries over inline citations when they conflict", correct: false },
      { letter: "C", text: "That the same fact appearing in different surface shapes — an inline citation and a bibliography entry — should resolve to the same normalized record", correct: true },
      { letter: "D", text: "To skip documents whose format was not shown in an example", correct: false },
    ],
    correct: "C",
    explanation: "\"(Smith, 2020)\" inline and \"Smith, J. (2020)...\" in a bibliography both resolve to the same {\"author\": \"Smith\", \"year\": 2020} record — the example teaches the model to extract past the surface formatting.",
  },
  {
    id: "t-pe-22",
    domain: "prompt-engineering",
    question: "How does the page recommend handling free-text quantities like \"two handfuls of rice\"?",
    options: [
      { letter: "A", text: "With a units-only glossary appended to the system prompt", correct: false },
      { letter: "B", text: "With a conversion example mapping the phrase to a normalized amount and unit, not just a unit list", correct: true },
      { letter: "C", text: "By rejecting informal quantities as unparseable", correct: false },
      { letter: "D", text: "By passing them through unchanged and converting downstream", correct: false },
    ],
    correct: "B",
    explanation: "Informal measurements need a conversion example: \"two handfuls of rice\" maps to {\"amount\": 100, \"unit\": \"g\"} at roughly 50g per handful. A unit list alone does not teach the conversion.",
  },
  {
    id: "t-pe-23",
    domain: "prompt-engineering",
    question: "In the page's severity rubric, which pairing of level and example is correct?",
    options: [
      { letter: "A", text: "CRITICAL — wrong sort order in a report", correct: false },
      { letter: "B", text: "HIGH — duplicated code", correct: false },
      { letter: "C", text: "MEDIUM — a logic bug with no immediate outage, such as an off-by-one error", correct: true },
      { letter: "D", text: "LOW — SQL injection", correct: false },
    ],
    correct: "C",
    explanation: "CRITICAL is a runtime failure for users (e.g., unhandled exception during payment), HIGH is a security vulnerability (SQL injection, XSS, missing authorization), MEDIUM is a logic bug without immediate outage, and LOW is code quality only.",
  },
  {
    id: "t-pe-24",
    domain: "prompt-engineering",
    question: "Which three failure modes does the page attribute to a single multi-file review pass?",
    options: [
      { letter: "A", text: "Attention dilution, inconsistent flagging, and missed obvious bugs", correct: true },
      { letter: "B", text: "Token overflow, rate limiting, and truncated diffs", correct: false },
      { letter: "C", text: "Higher cost, slower latency, and duplicate findings", correct: false },
      { letter: "D", text: "Schema violations, hallucinated file paths, and dropped severity labels", correct: false },
    ],
    correct: "A",
    explanation: "The more files stuffed into one context, the less scrutiny any single line gets; the model's internal bar shifts so the same pattern is caught in file A but missed in file D; and issues that would be one-shot catches in isolation get lost in the volume.",
  },
  {
    id: "t-pe-25",
    domain: "prompt-engineering",
    question: "When should prompt chaining be used instead of dynamic decomposition?",
    options: [
      { letter: "A", text: "When the scope only becomes clear after seeing intermediate results", correct: false },
      { letter: "B", text: "Whenever more than three files or documents are involved", correct: false },
      { letter: "C", text: "When the model must generate the next subtask from its current findings", correct: false },
      { letter: "D", text: "When the task is predictable and repeatable, with the steps and their order known in advance regardless of input", correct: true },
    ],
    correct: "D",
    explanation: "Chaining fits fixed pipelines like extract -> validate -> enrich that run the same way every time. Open-ended tasks whose scope emerges at runtime call for dynamic decomposition, where the model or an orchestrator generates the next subtask from current findings.",
  },
  {
    id: "t-pe-26",
    domain: "prompt-engineering",
    question: "For which error classes does the page say retry-with-feedback works?",
    options: [
      { letter: "A", text: "Information that is missing from the source document", correct: false },
      { letter: "B", text: "Format/structure violations and arithmetic or consistency errors", correct: true },
      { letter: "C", text: "Confident hallucinations the model is not aware of", correct: false },
      { letter: "D", text: "Any error class, as long as the retry count is high enough", correct: false },
    ],
    correct: "B",
    explanation: "Wrong types, missing required fields, and totals that don't match their parts are checkable against the document, so the model can re-derive the correct value. Absent data and confident hallucinations are the cases retry cannot fix.",
  },
  {
    id: "t-pe-27",
    domain: "prompt-engineering",
    question: "When a Pydantic ValidationError is raised in the retry loop, what does the page say to feed back to the model?",
    options: [
      { letter: "A", text: "str(error) directly, as the \"specific error\" in the retry prompt", correct: true },
      { letter: "B", text: "Only a boolean flag indicating that validation failed", correct: false },
      { letter: "C", text: "The full Python stack trace including library frames", correct: false },
      { letter: "D", text: "A regenerated JSON Schema with tighter constraints", correct: false },
    ],
    correct: "A",
    explanation: "On a ValidationError, str(error) goes straight back into the retry prompt as the specific error — the page notes it is the same message a human reviewer would want.",
  },
  {
    id: "t-pe-28",
    domain: "prompt-engineering",
    question: "How does dual-value self-correction relate to the validate-then-retry loop?",
    options: [
      { letter: "A", text: "It replaces the retry loop entirely once conflict_detected is in the schema", correct: false },
      { letter: "B", text: "It doubles cost, because every field requires two round trips", correct: false },
      { letter: "C", text: "It is a cheaper in-extraction check for whether the document agrees with itself, and composes with validate-then-retry for errors that need external context", correct: true },
      { letter: "D", text: "It only works when tool_use structured output is disabled", correct: false },
    ],
    correct: "C",
    explanation: "The discrepancy between stated_total and calculated_total surfaces immediately within a single extraction, without a second round trip. Cross-document or business-rule errors that require external checking still fall back to the validate-then-retry loop.",
  },
  {
    id: "t-pe-29",
    domain: "prompt-engineering",
    question: "According to the page, when should a schema field be marked `required`?",
    options: [
      { letter: "A", text: "Whenever the field is important to downstream consumers", correct: false },
      { letter: "B", text: "For every field, so the model never omits data", correct: false },
      { letter: "C", text: "Never — required fields are discouraged for model output", correct: false },
      { letter: "D", text: "Only when the field is always present; sometimes-absent fields should be nullable, with null treated as a real, valid answer", correct: true },
    ],
    correct: "D",
    explanation: "Marking a sometimes-absent field as required just forces bad data into it — the model fabricates a value to satisfy a required string. Genuinely absent information gets a nullable type like {\"type\": [\"string\", \"null\"]}.",
  },
  {
    id: "t-pe-30",
    domain: "prompt-engineering",
    question: "Which normalization rules does the page put in the prompt rather than the schema?",
    options: [
      { letter: "A", text: "Dates as Unix timestamps, currency as formatted strings, percentages as integers 0-100", correct: false },
      { letter: "B", text: "Dates as ISO 8601 with relative dates resolved to absolute, currency as a numeric amount plus ISO currency code, and percentages as decimal fractions", correct: true },
      { letter: "C", text: "Locale-specific date formats chosen per source document", correct: false },
      { letter: "D", text: "None — normalization is fully enforced by the JSON Schema", correct: false },
    ],
    correct: "B",
    explanation: "A schema constrains shape but not conventions like calendar format, so normalization rules belong in the prompt: \"next Friday\" becomes 2026-07-10, \"five bucks\" becomes {\"amount\": 5, \"currency\": \"USD\"}, and \"half\" becomes 0.5.",
  },
  {
    id: "t-pe-31",
    domain: "prompt-engineering",
    question: "Why does each request in a batch carry a `custom_id`?",
    options: [
      { letter: "A", text: "Batch responses can arrive out of order and separately from submission, so custom_id is the only reliable key joining a response to its request", correct: true },
      { letter: "B", text: "It sets the processing priority of the item within the batch", correct: false },
      { letter: "C", text: "It bills each item to a separate project or cost center", correct: false },
      { letter: "D", text: "It enables multi-turn conversations within a batch entry", correct: false },
    ],
    correct: "A",
    explanation: "The custom_id correlates each request to its response. Since results can come back out of order and detached from submission, it is the only reliable join key.",
  },
  {
    id: "t-pe-32",
    domain: "prompt-engineering",
    question: "What does the page say about tool use inside a Message Batches entry?",
    options: [
      { letter: "A", text: "Tool loops are supported but billed at the synchronous rate", correct: false },
      { letter: "B", text: "Each entry allows exactly one tool call and one follow-up turn", correct: false },
      { letter: "C", text: "Tool use works in batches as long as tool_choice is set appropriately", correct: false },
      { letter: "D", text: "A batch entry is single request to single response, so a workflow where Claude must call a tool and see its result before answering does not fit the batch model", correct: true },
    ],
    correct: "D",
    explanation: "There is no multi-turn conversation or tool-use loop within a batch entry. Workflows that need Claude to call a tool and observe the result before responding belong on the synchronous API.",
  },
  {
    id: "t-pe-33",
    domain: "prompt-engineering",
    question: "How does the page recommend handling a batch in which some items failed?",
    options: [
      { letter: "A", text: "Resubmit the entire original batch, since batches fail atomically", correct: false },
      { letter: "B", text: "Immediately switch the failed items to the synchronous API", correct: false },
      { letter: "C", text: "Iterate the results, identify failed entries by their custom_id, and resubmit only those as a new, much smaller batch", correct: true },
      { letter: "D", text: "Discard the failures, since the Batches API retries them internally", correct: false },
    ],
    correct: "C",
    explanation: "Batches do not fail atomically — some items succeed while others error out. Only the failed entries, found by custom_id, need to go into the follow-up batch.",
  },
  {
    id: "t-pe-34",
    domain: "prompt-engineering",
    question: "What does the page recommend doing before submitting tens of thousands of documents as a batch?",
    options: [
      { letter: "A", text: "Split the batch into hourly sub-batches to spread the risk", correct: false },
      { letter: "B", text: "Run the prompt against a small representative sample and iterate until it is reliable", correct: true },
      { letter: "C", text: "Submit the full batch once with a raised temperature to surface failure modes", correct: false },
      { letter: "D", text: "Duplicate every document so failures can be cross-checked", correct: false },
    ],
    correct: "B",
    explanation: "A prompt bug found after a 10,000-document batch means re-paying and re-waiting on the whole run; catching it on 50 documents is nearly free. Maximizing first-pass success is what makes batch economics pay off.",
  },
  {
    id: "t-pe-35",
    domain: "prompt-engineering",
    question: "Which workloads does the page assign to the Batches API versus the synchronous Messages API?",
    options: [
      { letter: "A", text: "Batch for non-blocking bulk work like overnight reports, 10,000+ document runs, and weekly audit sweeps; sync for anything blocking or interactive, like a pre-merge PR check a developer is waiting on", correct: true },
      { letter: "B", text: "Batch for all workloads over 100 requests, sync only for single requests", correct: false },
      { letter: "C", text: "Batch whenever cost matters, including interactive chat", correct: false },
      { letter: "D", text: "Sync for bulk work to get per-item retries, batch for chat responses", correct: false },
    ],
    correct: "A",
    explanation: "The dividing line is whether anyone is waiting synchronously: use batch when nobody is blocking on the result, and the synchronous API for any path where the caller cannot proceed until the answer arrives.",
  },
  {
    id: "t-pe-36",
    domain: "prompt-engineering",
    question: "In which situations does the page say the interview pattern is worth it?",
    options: [
      { letter: "A", text: "Only when the user explicitly asks Claude to pose questions", correct: false },
      { letter: "B", text: "Every task, since questions are always cheaper than any implementation", correct: false },
      { letter: "C", text: "Unfamiliar domains (fintech, healthcare, legal), tasks with non-obvious implications, and multiple viable approaches whose best choice depends on context not given", correct: true },
      { letter: "D", text: "Simple, well-specified tasks where the defaults are obvious", correct: false },
    ],
    correct: "C",
    explanation: "Asking first is cheaper than building the wrong thing and reworking it, and the questions themselves document the assumptions behind the design.",
  },
  // Adapted from avidevelops/claude-architect-exam-prep
  // (https://github.com/avidevelops/claude-architect-exam-prep, CC BY 4.0), condensed.
  {
    id: "t-pe-37",
    domain: "prompt-engineering",
    question: "What is the primary advantage of enforcing structured JSON output for tool responses and agent outputs in an agentic workflow?",
    options: [
      { letter: "A", text: "It makes the LLM's reasoning process deterministic", correct: false },
      { letter: "B", text: "It guarantees the semantic truth of data fetched from backend APIs", correct: false },
      { letter: "C", text: "It significantly reduces token consumption compared to prose", correct: false },
      { letter: "D", text: "Downstream systems and later agent steps can reliably read specific fields directly, without parsing free-form text", correct: true },
    ],
    correct: "D",
    explanation: "Structured output is a stable schema contract: downstream code references exact JSON keys instead of regex-parsing prose, which is what makes chained operations reliable. It does not make reasoning deterministic, does not validate semantic truth, and often costs *more* tokens than prose due to key and bracket overhead.",
  },
];
