import type { TheoryQuestion } from "@/domain/types";

export const toolMcpDesignTheory: TheoryQuestion[] = [
  {
    id: "t-tm-01",
    domain: "tool-mcp-design",
    question: "Which tool-definition field is the primary mechanism Claude uses to select a tool?",
    options: [
      { letter: "A", text: "name", correct: false },
      { letter: "B", text: "description", correct: true },
      { letter: "C", text: "input_schema", correct: false },
      { letter: "D", text: "tool_choice", correct: false },
    ],
    correct: "B",
    explanation: "Claude reads `description` fields, not source code, to decide which tool fits the current step. The `name` matters far less than most people assume, and vague descriptions are the most common cause of wrong-tool selection.",
  },
  {
    id: "t-tm-02",
    domain: "tool-mcp-design",
    question: "What are the three elements a strong tool description states?",
    options: [
      { letter: "A", text: "The tool's version, its author, and its rate limits", correct: false },
      { letter: "B", text: "The tool's name, its required fields, and its output type", correct: false },
      { letter: "C", text: "The underlying API endpoint, its authentication method, and its error codes", correct: false },
      { letter: "D", text: "What it does and returns, input formats with examples, and when to use it vs. a similar tool", correct: true },
    ],
    correct: "D",
    explanation: "A strong description states what the tool does and returns, its accepted input formats with examples (e.g., `user@domain.com`), and its boundary vs. similar tools (e.g., \"Use this tool BEFORE `lookup_order`\").",
  },
  {
    id: "t-tm-03",
    domain: "tool-mcp-design",
    question: "What does marking a field as `required` in an input schema actually mean?",
    options: [
      { letter: "A", text: "The information is always available at call time", correct: true },
      { letter: "B", text: "The field is important and should be prioritized by the model", correct: false },
      { letter: "C", text: "Claude will fail the call cleanly whenever the value is missing", correct: false },
      { letter: "D", text: "The application must validate the field before execution", correct: false },
    ],
    correct: "A",
    explanation: "`required` is a promise about availability, not a statement of importance. If a required field is sometimes missing from the input data, Claude will invent a plausible-looking value to satisfy the schema rather than fail the call — an important-but-sometimes-missing field belongs in the schema as optional and nullable.",
  },
  {
    id: "t-tm-04",
    domain: "tool-mcp-design",
    question: "What is the purpose of declaring a field's type as [\"string\", \"null\"]?",
    options: [
      { letter: "A", text: "It marks the field as required while allowing empty strings", correct: false },
      { letter: "B", text: "It tells the API to omit the field from the response", correct: false },
      { letter: "C", text: "It gives the model an explicit, valid way to say the information genuinely isn't there instead of hallucinating a value", correct: true },
      { letter: "D", text: "It allows the field to accept values of any data type", correct: false },
    ],
    correct: "C",
    explanation: "A nullable type union lets the model return `null` instead of fabricating a value to fill the slot. Any field describing information that might not exist in the underlying data should be nullable.",
  },
  {
    id: "t-tm-05",
    domain: "tool-mcp-design",
    question: "Which two enum values serve as escape hatches for a closed enum?",
    options: [
      { letter: "A", text: "\"none\" and \"unknown\"", correct: false },
      { letter: "B", text: "\"other\" and \"unclear\"", correct: true },
      { letter: "C", text: "\"misc\" and \"n/a\"", correct: false },
      { letter: "D", text: "\"default\" and \"skip\"", correct: false },
    ],
    correct: "B",
    explanation: "`\"other\"` is paired with a free-text detail field (e.g., `category_detail`) so information outside the predefined buckets isn't silently dropped, and `\"unclear\"` lets the model report genuine ambiguity instead of giving a confident wrong answer.",
  },
  {
    id: "t-tm-06",
    domain: "tool-mcp-design",
    question: "Which JSON Schema keyword enforces string shape, such as a 5-digit ZIP code?",
    options: [
      { letter: "A", text: "enum", correct: false },
      { letter: "B", text: "format", correct: false },
      { letter: "C", text: "minimum / maximum", correct: false },
      { letter: "D", text: "pattern", correct: true },
    ],
    correct: "D",
    explanation: "`pattern` enforces string shape (e.g., `^[0-9]{5}$` for a 5-digit ZIP), while `minimum`/`maximum` bound numeric ranges. These are cheap, deterministic guardrails that eliminate malformed output before it's ever executed.",
  },
  {
    id: "t-tm-07",
    domain: "tool-mcp-design",
    question: "Which class of errors does `tool_use` combined with a JSON Schema eliminate?",
    options: [
      { letter: "A", text: "Syntax errors, such as malformed JSON, wrong field types, or missing required fields", correct: true },
      { letter: "B", text: "Semantic errors, such as line-item totals that don't sum correctly", correct: false },
      { letter: "C", text: "Both syntax and semantic errors", correct: false },
      { letter: "D", text: "Neither — schema validation is purely advisory", correct: false },
    ],
    correct: "A",
    explanation: "The API enforces valid JSON matching the schema, eliminating syntax errors, but a response can be perfectly schema-valid and still wrong. Semantic errors require application-level validation and a retry loop that feeds the discrepancy back to the model.",
  },
  {
    id: "t-tm-08",
    domain: "tool-mcp-design",
    question: "Which `tool_choice` value forces Claude to call a specific named tool?",
    options: [
      { letter: "A", text: "{\"type\": \"auto\"}", correct: false },
      { letter: "B", text: "{\"type\": \"any\"}", correct: false },
      { letter: "C", text: "{\"type\": \"tool\", \"name\": \"verify_customer\"}", correct: true },
      { letter: "D", text: "{\"type\": \"forced\", \"tool\": \"verify_customer\"}", correct: false },
    ],
    correct: "C",
    explanation: "`{\"type\": \"tool\", \"name\": ...}` forces the named tool, `\"any\"` forces some tool (any one provided), and `\"auto\"` lets the model decide. Forcing is typically a one-shot move to guarantee a precondition runs first, followed by a switch back to `\"auto\"`.",
  },
  {
    id: "t-tm-09",
    domain: "tool-mcp-design",
    question: "In the tool_use cycle, how is a `tool_result` block linked to the tool call it answers?",
    options: [
      { letter: "A", text: "By repeating the tool's `name` field in the result", correct: false },
      { letter: "B", text: "By its position in the content array", correct: false },
      { letter: "C", text: "By the model's memory of its previous request", correct: false },
      { letter: "D", text: "By a `tool_use_id` matching the `id` of the `tool_use` block, sent as the next user turn", correct: true },
    ],
    correct: "D",
    explanation: "Your application executes the tool, then appends a `tool_result` block with the matching `tool_use_id` as the next user turn. Claude has no memory between requests, so every request must resend the full conversation history, including all prior tool calls and results.",
  },
  {
    id: "t-tm-10",
    domain: "tool-mcp-design",
    question: "Which `stop_reason` value means Claude is done and the result should be shown to the user?",
    options: [
      { letter: "A", text: "\"tool_use\"", correct: false },
      { letter: "B", text: "\"end_turn\"", correct: true },
      { letter: "C", text: "\"max_tokens\"", correct: false },
      { letter: "D", text: "\"stop_sequence\"", correct: false },
    ],
    correct: "B",
    explanation: "`\"end_turn\"` means the task is complete. `\"tool_use\"` means execute the requested tool and return a `tool_result`, `\"max_tokens\"` means the response was truncated, and `\"stop_sequence\"` means a configured stop sequence was hit.",
  },
  {
    id: "t-tm-11",
    domain: "tool-mcp-design",
    question: "What are MCP's three primitives?",
    options: [
      { letter: "A", text: "Tools, agents, and memories", correct: false },
      { letter: "B", text: "Servers, clients, and transports", correct: false },
      { letter: "C", text: "Tools, resources, and prompts", correct: true },
      { letter: "D", text: "Commands, files, and schemas", correct: false },
    ],
    correct: "C",
    explanation: "Tools are actions that can modify state or trigger side effects, resources are read-only context the model can pull in, and prompts are predefined templates exposed by the server. The key distinction: tools act, resources inform.",
  },
  {
    id: "t-tm-12",
    domain: "tool-mcp-design",
    question: "Which file holds project-level MCP server configuration that is version-controlled and shared with the team?",
    options: [
      { letter: "A", text: ".mcp.json at the project root", correct: true },
      { letter: "B", text: "~/.claude.json in the user's home directory", correct: false },
      { letter: "C", text: ".claude/settings.json in the project", correct: false },
      { letter: "D", text: "mcp.config.js committed to the repo", correct: false },
    ],
    correct: "A",
    explanation: "`.mcp.json` is committed to the repo so every teammate gets the same servers, with secrets referenced via `${VAR}` environment-variable substitution — the token itself is never committed. `~/.claude.json` is for personal servers, experiments, or one developer's credentials.",
  },
  {
    id: "t-tm-13",
    domain: "tool-mcp-design",
    question: "In the error category → action mapping, which `errorCategory` should typically be retried (often with backoff)?",
    options: [
      { letter: "A", text: "validation", correct: false },
      { letter: "B", text: "permission", correct: false },
      { letter: "C", text: "business", correct: false },
      { letter: "D", text: "transient", correct: true },
    ],
    correct: "D",
    explanation: "`transient` covers timeouts, 503s, and network blips — retry, often with backoff. `validation` means fix the input rather than retry unchanged, while `business` and `permission` should not be retried; structured errors also carry an explicit `isRetryable` boolean so the caller doesn't infer this from prose.",
  },
  {
    id: "t-tm-14",
    domain: "tool-mcp-design",
    question: "Which built-in Claude Code tool searches file contents?",
    options: [
      { letter: "A", text: "Glob", correct: false },
      { letter: "B", text: "Grep", correct: true },
      { letter: "C", text: "Read", correct: false },
      { letter: "D", text: "Bash", correct: false },
    ],
    correct: "B",
    explanation: "Grep matches text inside files (a function name, error string, or import), while Glob matches file paths and names (e.g., `**/*.test.tsx`). The recommended incremental pattern is Glob/Grep → Read → Grep → Read rather than reading everything up front.",
  },
  {
    id: "t-tm-15",
    domain: "tool-mcp-design",
    question: "What is the correct fallback when Edit fails because the target snippet appears more than once in the file?",
    options: [
      { letter: "A", text: "Read the full file, modify the content programmatically in memory, then Write it back", correct: true },
      { letter: "B", text: "Retry Edit with a slightly different snippet until one matches", correct: false },
      { letter: "C", text: "Use Write immediately to overwrite the file with just the new snippet", correct: false },
      { letter: "D", text: "Use Glob to locate another copy of the file and edit that one instead", correct: false },
    ],
    correct: "A",
    explanation: "Edit requires a unique text match and fails rather than guessing which occurrence was intended. The fallback is Read → modify programmatically (disambiguating by surrounding context or line position) → Write — used cautiously, since Write's replace-everything semantics risk clobbering unrelated content.",
  },
  {
    id: "t-tm-16",
    domain: "tool-mcp-design",
    question: "In the tool-design anti-pattern table, why do vague verbs like \"process\", \"handle\", and \"manage\" fail?",
    options: [
      { letter: "A", text: "They exceed the maximum length allowed for a tool name", correct: false },
      { letter: "B", text: "They cause the API to reject the tool definition as invalid", correct: false },
      { letter: "C", text: "They don't tell the model what changes state vs. what only reads", correct: true },
      { letter: "D", text: "They prevent the input_schema from being validated", correct: false },
    ],
    correct: "C",
    explanation: "Vague verbs give no signal about whether a tool mutates state or is read-only. The table's other rows: identical descriptions cause arbitrary/wrong selection, missing input examples make the model guess at format and possibly fabricate a value, and no stated boundary leaves the model unable to decide between overlapping tools.",
  },
  {
    id: "t-tm-17",
    domain: "tool-mcp-design",
    question: "When two tools genuinely overlap in function, what fix does the page recommend over writing a longer description?",
    options: [
      { letter: "A", text: "Rename and narrow scope — e.g., renaming analyze_content to extract_web_results", correct: true },
      { letter: "B", text: "Merge the two tools into a single tool with a combined schema", correct: false },
      { letter: "C", text: "Force the correct tool with tool_choice on every turn", correct: false },
      { letter: "D", text: "Remove one of the tools entirely from the tools array", correct: false },
    ],
    correct: "A",
    explanation: "Renaming removes the ambiguity at the name level itself, backed by a description that states the narrower purpose. This resolves overlap more reliably than piling more prose onto two still-overlapping descriptions.",
  },
  {
    id: "t-tm-18",
    domain: "tool-mcp-design",
    question: "What does tool_choice {\"type\": \"any\"} do?",
    options: [
      { letter: "A", text: "Lets the model decide whether to call a tool or respond in plain text", correct: false },
      { letter: "B", text: "Forces the model to call some tool — any one of those provided", correct: true },
      { letter: "C", text: "Forces the model to call one specific named tool", correct: false },
      { letter: "D", text: "Allows the model to invent a tool that wasn't in the provided list", correct: false },
    ],
    correct: "B",
    explanation: "`\"any\"` is for when you need guaranteed structured/tool-shaped output and don't care which tool fires, as long as one does. `\"auto\"` lets the model decide, and `{\"type\": \"tool\", \"name\": ...}` forces a specific tool.",
  },
  {
    id: "t-tm-19",
    domain: "tool-mcp-design",
    question: "Why is forcing a specific tool via tool_choice typically a one-shot technique rather than a steady-state setting?",
    options: [
      { letter: "A", text: "The API only accepts a forced tool_choice on the first request of a conversation", correct: false },
      { letter: "B", text: "Forcing a tool disables JSON Schema validation on subsequent turns", correct: false },
      { letter: "C", text: "Forced tool calls consume tokens at a higher rate", correct: false },
      { letter: "D", text: "Forcing on every turn removes the model's ability to recognize when no tool call is appropriate", correct: true },
    ],
    correct: "D",
    explanation: "The common pattern is to force a tool once to guarantee a precondition runs (e.g., `verify_customer` for identity verification), then switch back to `{\"type\": \"auto\"}` so the model can reason freely once that precondition is satisfied.",
  },
  {
    id: "t-tm-20",
    domain: "tool-mcp-design",
    question: "In the tool_use cycle, who actually executes the tool?",
    options: [
      { letter: "A", text: "Claude executes it directly against the external API or database", correct: false },
      { letter: "B", text: "Your application — Claude only emits a request to call the tool", correct: true },
      { letter: "C", text: "The Anthropic API executes it server-side and returns the result automatically", correct: false },
      { letter: "D", text: "The tool executes itself once its input passes schema validation", correct: false },
    ],
    correct: "B",
    explanation: "Claude does not execute tools itself — it responds with `stop_reason: \"tool_use\"` and a `tool_use` block containing `id`, `name`, and `input`. Your application calls the real API/DB/function and feeds the result back as a `tool_result` block.",
  },
  {
    id: "t-tm-21",
    domain: "tool-mcp-design",
    question: "What does stop_reason \"max_tokens\" indicate?",
    options: [
      { letter: "A", text: "The model finished the task and the result should be shown to the user", correct: false },
      { letter: "B", text: "A configured stop sequence was hit", correct: false },
      { letter: "C", text: "The response was truncated — you may need a higher token limit", correct: true },
      { letter: "D", text: "The tool call's input exceeded the schema's size constraints", correct: false },
    ],
    correct: "C",
    explanation: "`\"max_tokens\"` means the response was cut off, not complete. `\"stop_sequence\"` means a configured stop sequence was hit and should be handled per your application logic, while `\"end_turn\"` means Claude is done.",
  },
  {
    id: "t-tm-22",
    domain: "tool-mcp-design",
    question: "What is the Model Context Protocol (MCP)?",
    options: [
      { letter: "A", text: "A standard protocol for connecting Claude to external systems without bespoke integration code for every model-and-service combination", correct: true },
      { letter: "B", text: "A JSON Schema dialect used only for defining tool inputs", correct: false },
      { letter: "C", text: "Claude Code's internal format for storing conversation history", correct: false },
      { letter: "D", text: "A retry-policy specification for failed tool calls", correct: false },
    ],
    correct: "A",
    explanation: "MCP standardizes how Claude connects to data sources, APIs, and tools, so each integration doesn't need custom glue code. It exposes three primitives: tools, resources, and prompts.",
  },
  {
    id: "t-tm-23",
    domain: "tool-mcp-design",
    question: "In MCP, what is the \"prompts\" primitive?",
    options: [
      { letter: "A", text: "The system prompt the client sends with every request", correct: false },
      { letter: "B", text: "Free-text instructions the model writes back to the server", correct: false },
      { letter: "C", text: "Read-only context the model can pull in, such as a file or schema", correct: false },
      { letter: "D", text: "Predefined prompt templates exposed by the server, like a \"summarize this ticket\" template with server-defined variables", correct: true },
    ],
    correct: "D",
    explanation: "Prompts are server-exposed templates, distinct from the other two primitives: tools act (modify state or trigger side effects) and resources inform (read-only context).",
  },
  {
    id: "t-tm-24",
    domain: "tool-mcp-design",
    question: "Why do MCP resources exist, according to the page?",
    options: [
      { letter: "A", text: "To let the model trigger side effects without a tool definition", correct: false },
      { letter: "B", text: "To give the model or application an immediate \"map\" of what's available without making exploratory tool calls just to discover structure", correct: true },
      { letter: "C", text: "To cache prior tool results between API requests", correct: false },
      { letter: "D", text: "To store the server's authentication credentials", correct: false },
    ],
    correct: "B",
    explanation: "Resources are read-only context — a file, a database schema, a content catalog, documentation. A catalog of all project tasks or a schema gives an immediate map of what exists, so tools act while resources inform.",
  },
  {
    id: "t-tm-25",
    domain: "tool-mcp-design",
    question: "When is building a custom MCP server justified instead of using a community one?",
    options: [
      { letter: "A", text: "Only for unique, team-specific workflows that no community server covers", correct: true },
      { letter: "B", text: "Whenever you want extra control over a well-covered integration like GitHub", correct: false },
      { letter: "C", text: "For all standard integrations, since custom code is easier to audit", correct: false },
      { letter: "D", text: "Whenever the community server requires environment variables for secrets", correct: false },
    ],
    correct: "A",
    explanation: "For standard integrations like GitHub, Jira, and Slack, prefer existing community servers — they're already tested against the target API's quirks and maintained independently of your project. Custom servers are justified by uniqueness (e.g., a proprietary internal system), not by a desire for extra control.",
  },
  {
    id: "t-tm-26",
    domain: "tool-mcp-design",
    question: "In a structured tool error, what is the purpose of the attempted_query field?",
    options: [
      { letter: "A", text: "It tells the caller whether the failure is safe to retry", correct: false },
      { letter: "B", text: "It classifies the failure so the caller can decide how to react", correct: false },
      { letter: "C", text: "It records what was actually sent, so a retry can adjust the right parameter instead of guessing", correct: true },
      { letter: "D", text: "It stores the human-readable explanation of the failure", correct: false },
    ],
    correct: "C",
    explanation: "`attempted_query` shows what was actually sent (e.g., `order_id=12345`). The other fields cover the distractors: `isRetryable` is the explicit retry boolean, `errorCategory` classifies the failure, and `message` is the human-readable supplement to the structured fields, not a replacement for them.",
  },
  {
    id: "t-tm-27",
    domain: "tool-mcp-design",
    question: "What does the partial_results field in a structured error carry?",
    options: [
      { letter: "A", text: "The server-side stack trace of the exception", correct: false },
      { letter: "B", text: "The subset of the input schema that failed validation", correct: false },
      { letter: "C", text: "The number of retries already attempted", correct: false },
      { letter: "D", text: "Anything usable that was recovered before the failure, so a partial failure doesn't discard everything", correct: true },
    ],
    correct: "D",
    explanation: "Returning `partial_results` lets the caller keep whatever was recovered before the failure. Aborting the entire operation on the first failure instead of returning partial results is one of the listed server-side anti-patterns.",
  },
  {
    id: "t-tm-28",
    domain: "tool-mcp-design",
    question: "What is the typical action for an error with errorCategory \"validation\"?",
    options: [
      { letter: "A", text: "Fix the input — do not retry unchanged", correct: true },
      { letter: "B", text: "Retry, often with backoff", correct: false },
      { letter: "C", text: "Surface to the user or escalate without modifying anything", correct: false },
      { letter: "D", text: "Swap in different credentials and retry", correct: false },
    ],
    correct: "A",
    explanation: "`validation` covers malformed input or a missing required parameter, so retrying the same call unchanged just fails again. `transient` is the retry-with-backoff category, `business` should be surfaced or escalated, and `permission` needs different credentials or human intervention — neither should be retried.",
  },
  {
    id: "t-tm-29",
    domain: "tool-mcp-design",
    question: "Which of these is listed as a server-side error-handling anti-pattern?",
    options: [
      { letter: "A", text: "Returning an explicit isRetryable boolean", correct: false },
      { letter: "B", text: "Silently treating an empty result as success", correct: true },
      { letter: "C", text: "Classifying failures with an errorCategory field", correct: false },
      { letter: "D", text: "Returning partial results after a mid-operation failure", correct: false },
    ],
    correct: "B",
    explanation: "The listed anti-patterns are: generic status strings with no category, silently treating an empty result as success, aborting the entire operation on the first failure instead of returning partial results, and retrying indefinitely without a cap regardless of category.",
  },
  {
    id: "t-tm-30",
    domain: "tool-mcp-design",
    question: "Which built-in Claude Code tool runs shell commands such as git, package manager commands, tests, and builds?",
    options: [
      { letter: "A", text: "Edit", correct: false },
      { letter: "B", text: "Glob", correct: false },
      { letter: "C", text: "Read", correct: false },
      { letter: "D", text: "Bash", correct: true },
    ],
    correct: "D",
    explanation: "Bash is the shell runner for git, package managers, tests, and builds. Glob finds files by path/name pattern, Read loads a file in full, and Edit replaces a snippet via a unique text match.",
  },
  {
    id: "t-tm-31",
    domain: "tool-mcp-design",
    question: "What is the purpose of the built-in Write tool?",
    options: [
      { letter: "A", text: "Append content to the end of an existing file", correct: false },
      { letter: "B", text: "Replace a snippet in an existing file via a unique text match", correct: false },
      { letter: "C", text: "Create a file from scratch, or perform a full rewrite of one", correct: true },
      { letter: "D", text: "Search file contents for a function name or error string", correct: false },
    ],
    correct: "C",
    explanation: "Write creates a new file or fully rewrites one, with replace-everything semantics. That's why Edit is preferred for precise in-place changes whenever a unique match is available — Write risks clobbering unrelated content.",
  },
  {
    id: "t-tm-32",
    domain: "tool-mcp-design",
    question: "What is the recommended incremental investigation cycle in Claude Code?",
    options: [
      { letter: "A", text: "Glob/Grep to find entry points → Read those files → Grep for usages of what you read → Read the consumer files → repeat", correct: true },
      { letter: "B", text: "Read every file up front, then Grep the loaded content for relevant symbols", correct: false },
      { letter: "C", text: "Bash to dump the entire tree, then Edit files as needed", correct: false },
      { letter: "D", text: "Write a summary file first, then Glob for matches against it", correct: false },
    ],
    correct: "A",
    explanation: "The Glob → Grep → Read → Grep → Read cycle builds understanding incrementally, keeping context focused on what's relevant to the current question instead of front-loading the entire codebase before knowing what matters.",
  },
  {
    id: "t-tm-33",
    domain: "tool-mcp-design",
    question: "Which of these is listed as a built-in tool anti-pattern?",
    options: [
      { letter: "A", text: "Using Grep to search file contents for an error string", correct: false },
      { letter: "B", text: "Reporting findings without a precise file:line reference", correct: true },
      { letter: "C", text: "Reading a file in full before editing it", correct: false },
      { letter: "D", text: "Confirming scope before running a destructive Bash command", correct: false },
    ],
    correct: "B",
    explanation: "\"There's a bug in the auth module\" is not actionable; \"the null check is missing at auth.ts:42\" is. The other listed anti-patterns are reading all files at once, overly broad Glob patterns (e.g., `**/*` across a monorepo), and unsafe Bash — destructive commands like broad deletes, force-pushes, or unscoped rm without confirming scope first.",
  },
];
